### ISSUE TITLE
SEO form can't save empty value

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1000]
### Steps to reproduce

- Open page in edit mode
- Click on "SEO" button inside "Page" group
- Empty pagetype field and save

### Expected result

Page type saved with empty value

### Actual result

`Uncaught TypeError: Cannot read property 'pagetype' of undefined`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

- If the issue was encountered on a site, please attach your `package.json`
- If the issue was encountered in the Bodiless-JS repo, please link to a
  commit or branch on which the issue occurs.

**Comment by konst8** [comment]
@dewen I was able to save the form with an empty page type field at the master branch.
Could you check if the issue is still actual and specify details to reproduce if so. Thanks.

**Comment by TatsianaMiraniuk** [comment]
not reproduced in Test Site
