### ISSUE TITLE
Edit env: 'Warning: React does not recognize the `canonicalPreset` prop on a DOM element.' is in a console

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1016]
## Description
*Description:* Edit env: 'Warning: React does not recognize the `canonicalPreset` prop on a DOM element.' is in a console
 *URL/Component*: PDP
 *Screenshots:* 
 *Testing Environment:* Edit env
 *Clarification:* find the root cause and address the issue

**Comment by dewen** [comment]
This might relate to canonicalPreset prop from previous GatsbyImage component, applied to `img` tag.

```
<GatsbyImage {...omit(rest, 'canonicalPreset', '_nodeKey')} alt={alt} image={imageData} />
```

it might have been fixed in current Bodiless Gatsby Image component.
