### ISSUE TITLE
Context menu does not display for full-bleed items

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#1031]
## STR
Create a full-bleed component which has a context menu )eg flow container)
click on the component in edit mode

## ER
local context menu appears

## AR
local context menu does not appear

The local context menu will appear if you make the component slightly smaller than the viewport (eg `width: 99.9vw`

**Comment by allencit** [comment]
When the component(eg. flow container) has 100% width of the viewport, the left position of the context menu is 0 and invisible, please see the fix: https://github.com/johnsonandjohnson/Bodiless-JS/pull/1093
