### ISSUE TITLE
Edit mode: Impossible to navigate to the next slide in carousel without dots or/and NavButtons

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1058]
## Description

It is impossible to add image to the carousel slides except first one in autoplay carousel without dots and NavButtons
### Steps to reproduce

1. In **edit** mode go to /carousel/ page
2. Scroll till "Only Autoplay with default interval" or "Autoplay with 10 second interval" carousel type
3. Add >1 slides
4. Try to add images to the 2nd, 3rd, etc slides 
### Expected result

It should be possible to move to the next slide in edit mode when carousel has no Navigation buttons or/and dots.

### Actual result

All slides after 1st one are inaccessible in edit mode, as there is no possibility to slide to the next.

**Comment by schristodoulou** [comment]
This is expected behavior. We do not expect to provide the user a carousel without navigation.
