### ISSUE TITLE
Carousel RTL: Card Title and Body Text in Chameleon Carousel "Horizontal Card" is not RTL

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1060]
## Description

Horizontal Card Carousel has LTR direction on RTL page

### Steps to reproduce

1. Go to the /carousel/rtl/ page
2. Scroll to the Cameleon carousel type
3. In edit mode click 'Swap' carousel in local context menu.
4. Select "Horizontal Card" carousel
5. Observe placeholder text (Title, Body)

### Expected result

Placeholder text has RTL direction

### Actual result

Placeholder text has LTR direction

<img width="658" alt="carousel-rtl" src="https://user-images.githubusercontent.com/81805756/131347254-11c17fb3-cea3-466e-b209-627a2197c802.png">

**Comment by ValeryRudko** [comment]
It is not reproducible anymore, those closed.
Current view is 
![image](https://user-images.githubusercontent.com/39922356/163813367-8a9df485-195b-4606-9a73-0983097d01a0.png)

**Comment by hvanyo** [comment]
per @ValeryRudko  says its not reproducable so thus closing.
