### ISSUE TITLE
Error page is appearing when try to add/swap component from caption 

### ISSUE THREAD

**Issue by AshuraHassan** [johnsonandjohnson/Bodiless-JS#1065]
https://user-images.githubusercontent.com/88794909/133194121-683fac25-7e7e-48bb-b139-a0f5bb61fb0e.mp4

# Description

In Edit mode after adding link to caption when try to swap or add components getting error message

### Steps to reproduce

1. Goto https://edit.master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/gallery-final/
2. Click Edit icon
3. Add Flow container
4. Enter caption below gallery
5. Select Caption and click link
6. Click caption and click swap / add button from component

### Expected result

flow container should be swap

### Actual result

Getting error message page

### Environment

master

### Affected Version

master

Attached video recording for reference

**Comment by TatsianaMiraniuk** [comment]
fixed by #1197
