### ISSUE TITLE
Filter content (categories, groups) invisible on static 

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1068]
## Description

Created content inside filter block is invisible on Static. As a workaround screen size can be adjusted to the tablet/mobile mode and then turned to the previous sizec, then the content becomes visible.

### Steps to reproduce

1. Create any content in Filter block from Edit mode on any page with Filter, e.g. /products/
2. From static mode go to the /products/ page
3. Observe Filter block

### Expected result

Created content (Categories, Groups) are exist and displayed in Filter block

### Actual result

Filter block is empty. Content is not visible to user. Adjusting screen size to the smaller one and turning it back works as workaround and makes content visible.
Please see videocast:

https://user-images.githubusercontent.com/81805756/131855973-819201db-0159-4d19-88ec-388be131c1f0.mp4

### Affected Version

Reproducible in [master](https://master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/)

**Comment by TatsianaMiraniuk** [comment]
fixed by #1339
