### ISSUE TITLE
Mobile, Tablet ~<700px Chameleon Compound List requires additional padding on the left side.

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1072]
## Description

 Numbers or Bullets before 1st Level List item of the are hidden on some screen resolutions: [<700]; [1006;1060]; [1260;1326]
### Steps to reproduce

1. Add Cameleon Compound list component on the /flow-container/ page
2. Adjust screen resolution to one of the following sizes:[<700]; [1006;1060]; [1260;1326] and observe Numbers or bullets before 1st level item
### Expected result

Numbers, Bullets are visible on screen minimizing

### Actual result

Numbers/Bullets are getting hidden

https://user-images.githubusercontent.com/81805756/132004947-fed2a1e3-949b-4ee5-84a9-6cbdf9027fc7.mp4

### Affected Version

reproducible on [master](https://master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/)

**Comment by asiarheyeu** [comment]
Closed as a low priority bug
