### ISSUE TITLE
Able to collapse, non collapsible accordion via keyboard space key

### ISSUE THREAD

**Issue by AshuraHassan** [johnsonandjohnson/Bodiless-JS#1076]
## Description

Non collapsible accordions are able to collapse via keyboard using space key

### Steps to reproduce

1. Goto to /accordion/ on Edit Env
2. Click edit icon
3. Move control to non collapsible accordion via keyboard using Tab key
4. Click space key 

### Expected result

Non collapsible accordion should not be collapsed by keyboard and mouse 

### Actual result

Non collapsible accordion are able to collapse by keyboard

### Environment

master

### Affected Version

master env

**Comment by TatsianaMiraniuk** [comment]
this is a duplicate of #1008

**Comment by asiarheyeu** [comment]
Bug scrub notes: reproducible in static mode as well
