### ISSUE TITLE
User can disable links of a page when a page is disabled

### ISSUE THREAD

**Issue by e2thex** [johnsonandjohnson/Bodiless-JS#1086]
## Description
As a site editor, I want to mark a page as one that should temporarily not be linked to from any link.

## User Story
AS A site user/content editor,
I WANT to mark a page as not accessible to links
SO THAT I can temporarily disable links to the page from anywhere on the site..
### Acceptance Criteria
AC1. 
 If the Page is fully disabled then 
The static(Preview) site will not render the "href" for any inbound link (the text will display but it will not be a link)

AC2.
The link will function as expected in edit view no matter the enable/disable allocation

AC3.
The Documentation is updated to include how a user can turn this on and what will happen

### Implementation Notes
Where do we keep the list of disable pages?
Need a mechanism api to look in this store and then behave appropriately.
Potential 4 items we need to determine how to exclude/change behavior approriately per build(gatsby-plugin-exclude)/sitemap.xml(gatsby-plugin-sitemap)/list & menu & search component.
We think that breadcrumb link will land in AC5.
### References
UX: https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9. (note: we are doing sections in the submenu)
Put the move button after the new in the page menu.

**Comment by e2thex** [comment]
## Description
As a site editor, I want to mark a page as one that should temporarily not be linked to from any link.

## User Story
AS A site user/content editor,
I WANT the mark a page as not link able
SO THAT I can temporarily hide links to the page from anywhere on the site..
### Background/Description

### Acceptance Criteria
AC1.
WHEN the user is in the Edit UI and in EDIT mode
THEN there is a "Page" icon in the Admin Menu
AND when the User selects the Page Icon
THEN The sub page menu form panel window opens
AND when the user selects the Disable Page icon
There is an option to disable incoming links. as well as disable the whole page
AC2.
When the enable is click the user is presented with the message "..." and the icon changes back to enable icon

AC3. When there is nothing disable the icon change back to not enabled icon

AC4.
If inbound links are disabled then 
The static(Preview) site will not render the href for any inbound link (the text will spread but it will not be a link)

AC5.
If the Page is fully disabled then 
The static(Preview) site will not render the href for any inbound link (the text will spread but it will not be a link)

AC6.
The link will function normally in edit.

### Implementation Notes
Where do we keep the list of disable pages?
Need a mechanism api to look in this store and then behave appropriately.
Potential 4 items we need to determine how to exclude/change behavior approriately per build(gatsby-plugin-exclude)/sitemap.xml(gatsby-plugin-sitemap)/list & menu & search component.
We think that breadcrumb link will land in AC5.
### References
UX: https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9. (note: we are doing sections in the submenu)
Put the move button after the new in the page menu.

**Comment by asiarheyeu** [comment]
Completed. Closing
