### ISSUE TITLE
Multiple slate editors on same page cause keyboard lag

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#112]
## Description

Multiple slate editors on same page cause keyboard lag

### Steps to reproduce

1. Place many slate editors on the same page (eg on slate-api page, add >20 copies of the same editor, pointing to different nodes

### Expected result

Editors are as responsive to kestrokes as if there is only one.

### Actual result

Editors exhibit significant keyboard lag.

**Comment by beliayeu** [comment]
fixed in https://github.com/johnsonandjohnson/Bodiless-JS/pull/104
