### ISSUE TITLE
Html-deserializer: Content in 'Output' disappear when make any changes in 'Supply HTML to Flow Container' after adding new component on the page

### ISSUE THREAD

**Issue by inesa-hapeyeva** [johnsonandjohnson/Bodiless-JS#1124]
https://user-images.githubusercontent.com/31862315/135286701-ef622572-6ee8-467c-a95a-da456af5388e.mp4

### Description 
After adding a new component on the page any changes with html code will remove component with corresponding content in 'output'

### Steps to reproduce
1. go to /flow-container/html-deserializer/ page (Master edit mode)
2. observe 'Output', content there corresponds to html code in 'Supply HTML to Flow Container'
3. add any new component
4. in 'Supply HTML to Flow Container' make any changes
5. observe 'Output'

### Expected result
Сontent in 'output' corresponds to html code in 'Supply HTML to Flow Container'

### Actual result
Component with corresponding content in 'output' disappear

6. Delete a newly component
7. Repeat steps 4-5
### Expected result
Сontent in 'output' corresponds to html code in 'Supply HTML to Flow Container'

### Actual result
Component with corresponding content in 'output' disappear

**Note:** Clicking 'Revert' in local context menu of the newly-added component returns the correct behavior

### Environment

Reproducible in[ Master](https://edit.master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/)

**Comment by schristodoulou** [comment]
Won't Fix.
