### ISSUE TITLE
[GAP] Youtube: buttons Play'/'Stop' from 'YouTube Player API' don't get bordered on focus

### ISSUE THREAD

**Issue by inesa-hapeyeva** [johnsonandjohnson/Bodiless-JS#1130]
### Description
Buttons Play'/'Stop' from 'YouTube Player API' don't get bordered on focus

### Steps to reproduce
1. Go to /youtube/ page (edit/static env)
2. Scroll down to 'YouTube Player API'
3. Click 'Play'/'Stop' button
4. Observe buttons border color
### Expected result

buttons bordered on focus (Master env)

### Actual result

buttons don't get bordered on focus

https://user-images.githubusercontent.com/31862315/135599874-a6328945-379a-4ced-a7b2-95131e82c557.mp4

Note:
Introduced by [#1056 ](https://github.com/johnsonandjohnson/Bodiless-JS/pull/1056)

**Comment by asiarheyeu** [comment]
Closed as trivial bug. Won't fix
