### ISSUE TITLE
Informed latest package blocks new/clone creation when upgrading

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1171]
## Description
*{color:red}In both https://jira.jnj.com/browse/AESQ-7528 & https://jira.jnj.com/browse/AESQ-4345
we have solved the problem by forcing the informed package to use 3.13.1.
We should take time to investigate and fix this bug so we can upgrade in future upgrade dependency{color}*

**Steps to Reproduce:**
0 Upgrade to latest pacakge on Informed 

 1. in Edit env, open any page, except Home, e.g. /accordion/
 2. switch to Edit mode
 3. click '+Page'
 4. type a page name, e.g. page_1
 5. click 'Edit' below Page Path -> URL is /accordion/page_1
6. click 'v' to save the new page
 *Actual Results:*
 'No special characters or spaces allowed' shows, the page is not created.
 !Screen Shot 2021-02-17 at 1.33.14 PM.png|thumbnail! 

**Expected Result:**
the slashes are expected to be allowed. the new page is created for that example.

NOTE:  also creats this bug

**Comment by asiarheyeu** [comment]
Closing as completed
