### ISSUE TITLE
Duplicating Images on Cloned paged

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#1177]
## Description
As a Site Builder, I want the assets to be independent when cloning the page, so that any changes I make do not affected the copied page. 
## Acceptance Criteria 
AC1.

When A page is cloned that has uploaded assets 
Each asset is copied into the namespace of the new page and the data is updated to point to those assets.

Note: The assets on the source page are assumed to be already in the correct namespace.

**Comment by asiarheyeu** [comment]
Closing as completed
