### ISSUE TITLE
Move Assets on Moved paged

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1198]
## Description
As a Site Builder, I want the assets to be move when the user moves the page, so that any assets are moved into the new namespace.

## Acceptance Criteria 
AC1.

When A page is moved that has uploaded assets 
Each asset is moved into the namespace of the moved page and the data is updated to point to those assets.

Note: The assets on the source page are assumed to be already in the correct namespace.

**DUE to technical limitations encountered during implementation** we are 'copying assets to new location and data is updated to point to these assets" and we will purge assets on build in this ticket: https://github.com/johnsonandjohnson/Bodiless-JS/issues/1348

**Comment by asiarheyeu** [comment]
Fixed with #1326
