### ISSUE TITLE
Component Selector:  an unexpected 'Category' section with 'Appearance', 'Orientation', 'Structure' options shows up in Filter area

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#1242]
**Steps to reproduce**
1. open /flow-container/ in Edit env, Edit Mode
2. open Component Selector (click on any Flow Container)
3.  click Card under 'Type' Section
4. click 'No CTA' under 'Card Structure' Section (or any other option with 'No..')

**Actual result**
'Category' section with 'Appearance', 'Orientation', 'Structure' options shows up. Selecting any of them doesn't  do anything

![Screen Shot 2021-11-18 at 12 48 15 PM](https://user-images.githubusercontent.com/3224040/142470198-d3bd619a-7a05-4b1c-a6ec-6cc2956d0ec2.png)

**Expected result**
'Category' section with 'Appearance', 'Orientation', 'Structure' is hidden

Reproduced in Main

**Comment by asiarheyeu** [comment]
Closing as won't fix due to a low priority
