### ISSUE TITLE
Attempt to clone some pages throws 'Failed to compile' error

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1248]
## Description

Attempt to clone some pages, e.g. /accordion/, /flow-container/, rtl pages etc. (mainly under 'Components' tab) throws 'Failed to compile error'. But **PLP, PDP, or newly created Default pages are cloning successfully.**

### Steps to reproduce
1. Locally In edit env edit mode go to one of the pages under 'Components' menu tab, e.g. /accordion/
2. In sidebar menu click 'Page' -> 'Clone'. Enter utl path of cloned page and click 'V' to save.

### Expected result

The page is cloned and the link to the newly-cloned page is provided

### Actual result
Error:
"Failed to compile
./src/data/pages/accordion/clone/index.tsx
Open in editor
Source
./src/data/pages/accordion/clone/index.tsx
Module not found: Can't resolve '........componentsLayout' in 'C:\test-clone\Bodiless-JS\examples\test-site\src\data\pages\accordion\clone'
This error occurred during the build process and can only be dismissed by fixing the error."
<img width="950" alt="Screenshot_1" src="https://user-images.githubusercontent.com/81805756/142828263-b7d6f5be-00ae-449b-9d99-0f4a392e8bab.png">

### Affected Version
reproduced on main

**Note: Not reproduced on p.sh env**

**Comment by TatsianaMiraniuk** [comment]
fixed in https://github.com/johnsonandjohnson/Bodiless-JS/tree/bugfix/1248-clone-on-windows
