### ISSUE TITLE
BurgerMenu: an item with a reference to a disabled page is not visible in Edit Mode

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#1249]
**Steps to reproduce**
1. open Home page in Edit env, Edit Mode
2. in MegaMenu, add a link to a disabled page in Top level Menu item  -> The item is highlighted as disabled (all as expected)
3.  change Browser width to Tablet view and click Burger Menu

**Actual result**
Top level Menu item from step#2 is not shown

![Screen Shot 2021-11-22 at 4 12 43 PM](https://user-images.githubusercontent.com/3224040/142936742-fcf35d58-0665-46bc-8232-f7a043f25e72.png)
![Screen Shot 2021-11-22 at 4 12 52 PM](https://user-images.githubusercontent.com/3224040/142936736-d7ae6532-c04d-4ad8-af71-0c38ff0b66fc.png)

**Expected result**
the item is visible because it's still Edit Mode ?? 

Reproduced in Main

**Comment by schristodoulou** [comment]
Won't fix.
