### ISSUE TITLE
Files with a size >1MB failed to be uploaded and the session is terminated in terminal when running locally

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1262]
## Description

Attempt to upload a file with a more than ~1.1 mb to the links or linkable images failed to be uploaded and the session in terminal is terminated with an error "Error: EBUSY: resource busy or locked" and "Upload failed, please try again" in UI.

### Steps to reproduce
1. Locally in Edit env edit mode go to any pages where link can be applied. 
2. Upload a document with a file size ~>1.1 mb for example 
[file-sample_1,37MB.pdf](https://github.com/johnsonandjohnson/Bodiless-JS/files/7650446/file-sample_1.37MB.pdf)
 to a link using either a file manager or drag&drop
### Expected result
TBD: File uploaded or there is an error saying that the file is too large.

### Actual result

Session in terminal is terminated with an error and there is an error in UI

### Environment

reproduced on main

**Comment by hvanyo** [comment]
Uploaded file and this appears to be resolved and thus closing
