### ISSUE TITLE
flow-container: There is no Delete button in Local Context Menu of 'FlowContainer restricted to 1 item'

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#1269]
There is no Delete button in Local Context Menu of 'FlowContainer restricted to 1 item'

**Steps to reproduce:**
1. open /flow-container/ in Edit env, Edit Mode
2. click inside FlowContainer restricted to 1 item
3. click Add to open Component Selector
4. add any component
5. click the component to delete it (to clear the flow container)

**Actual result**
there is no 'Delete' button, only 'Swap' button available

![Screen Shot 2021-12-03 at 7 44 44 PM](https://user-images.githubusercontent.com/3224040/144689900-6944b8c5-331e-4d54-91bc-c7bb16fb6d07.png)

**Expected result**
Delete button is available. It's possible to clear the flow container

Reproduced in Main

**Comment by hvanyo** [comment]
DOC: minComponents https://edit.main-bvxea6i-gc5fzrr5cpumq.us-2.platformsh.site/___docs/#/bodiless/Components/FlowContainer?id=limit-number-of-components

**Comment by TatsianaMiraniuk** [comment]
'FlowContainer restricted to 1 item' originally allowed to delete the component, it was a limit for max number of components but no limit on **minimum** amount. 
![Screen Shot 2021-12-13 at 10 23 46 AM](https://user-images.githubusercontent.com/3224040/145844999-2d3e794e-9722-489f-8dab-7f85f732fae3.png)


The restriction to have 1 component minimum for that FC in Test Site added in #926 (https://github.com/johnsonandjohnson/Bodiless-JS/pull/926/files#diff-9c1bc974f0a37f3bb4b3bafe48b605e5af03c501a77263304a1f86933515c546R92)
