### ISSUE TITLE
Delete Assets from the Name Space of the Page

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#1292]
## Description
As a Site Builder, I want the assets deleted when the user deletes the page, so they don't populate the repo.

RISK:
"Image media and other items would persist in system as we have no way to tell if the media items are being reused."

We purposely descoped in https://jira.jnj.com/browse/AESQ-3057 / https://github.com/johnsonandjohnson/Bodiless-JS/issues/392

## Acceptance Criteria
AC1. Any assets that use the Name Space of a Deleted page are removed from the repository

**Comment by hvanyo** [comment]
This passes UAT.
