### ISSUE TITLE
eslint is not detecting common syntax issue

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1327]
## Description

Expect `npm run lint` and VSCode to report lint issues.

### Steps to reproduce

- run `npm run setup`
- update ts/js file with trailing space on some lines
- run `npm run lunt`

### Expected result

- error report: Trailing spaces not allowed.eslintno-trailing-spaces

### Actual result

- No lint errors

**Comment by asiarheyeu** [comment]
Closing as completed
