### ISSUE TITLE
Forms Should Close When 1 is in Use

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#133]
## User Story

- AS A Content Editor
- I WANT only one form interaction at a time
- SO THAT I do not confuse the functionality I am interacting with. 

### Background/Description

Example use case: When a user selects to use the component switcher they can also add components which can be confusing to the user. 
### Acceptance Criteria

AC.
GIVEN that I am in the edit/review UI
WHEN I interact with a form element (menu & context)
THEN only 1 form can be used at a time.  

### References

- Component Switcher - https://github.com/johnsonandjohnson/Bodiless-JS/issues/69

**Comment by wodenx** [comment]
implemented
