### ISSUE TITLE
Add Metadata with GIT Values (Bodiless)

### ISSUE THREAD

**Issue by CourtLC77** [johnsonandjohnson/Bodiless-JS#1331]
## Description
*Description:* As a site builder I will need a way to capture the repository in GIT Values of the page I wish to copy the Target and Commit Hash

 
1. Writes a metatag when page is rendered
1. Provides an API that supplies the GIT ref

 

 Component gets dropped on page template that creates the metatag 

 

**Implementation Notes**
**One way of doing this is via Gatsby SSR

Another way is by a component that queries a Bodiless backend - Only happens when on the server because not available on the static site

This does not include the edit environment
To test AC3 we can implement on the test site
 
**Technical Notes**

In implementation, provide a fairly flexible way configurable by site builder to specify name of template (or templates) for whitelisting what templates generate metadata. aka _default, PDP, etc..

_Note: We will NOT Encrypt we will use JS Obfuscate as we don't believe the three pieces of information are sensitive enough to necessitate Encryption_

 

 
## Acceptance Criteria
AC1: All pages that are default templates on the site should automatically  contain the Repository URL and Commit Hash (Optionally); pages that are not default templates should not receive the metadata metatag at this time

AC2: The metadata should be names 'siteinfo' 

AC3: Make an API available so the downstream consumer can use to change the function gets the repository and git hash and can modify how they wish

**Comment by irkhodzka** [comment]
on behalf of Halina closing as completed
