### ISSUE TITLE
Menu arrow down is displayed as text "expand_more" on static

### ISSUE THREAD

**Issue by irkhodzka** [johnsonandjohnson/Bodiless-JS#1344]
### Steps to reproduce
In edit mode add menu item
Create a sub-item of any type
Add a link to the main menu item, so that 'arrow down' icon appeared 
From static observe the created menu item
### Expected result

 icons displaued instead of text

### Actual result

"expand_more" is displayed instead of  'arrow down' icon

### Affected Version

reproduced on main
![Screen Shot 2022-04-15 at 1 10 32 PM](https://user-images.githubusercontent.com/3224040/163600202-4f2e91b7-7d42-4017-bb62-646997b37d9e.png)

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/1553
