### ISSUE TITLE
Brand.com Header

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1354]
## User Story
As site owner/builder, I want a header that has Brand.com applied to it and can reuse so I have efficient site build process.

## Designs
* https://xd.adobe.com/view/fd6e4dde-2ecf-480a-aaaf-f5043cb04bf0-a83d/screen/61a2aa2d-eab9-458d-ae0b-c49e08ebea27/specs/

## Acceptance Criteria
AC1 Package cx-layout contains cxHeader component follows responsive brand.com design
- including the Logo : Logo component is a clickable **gatsby image** as a **gatsby link** defaulting to href="/" and loads as eager.
- other components are placeholders

AC2 cxHeader is in the cx-starter package

AC3 cxHeader is activated on a component page within the Bodiless Test Site

## Notes

- Items in bold (in ACs) are different behavior the previous implemented header.

**Comment by hvanyo** [comment]
Updated NAMES to correct names:
package = cx-layout
component = cxHeader & cxLogo

**Comment by irkhodzka** [comment]
closing on behalf of Halina
