### ISSUE TITLE
Brand.com Typography, Plain Editor, Rich Text Editor

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1361]
## Description
As site owner/builder, I want the typography for Brand.com available as package and can reuse so I have efficient site build process.

## Designs
* [Typogrpahy ](https://xd.adobe.com/view/fd6e4dde-2ecf-480a-aaaf-f5043cb04bf0-a83d/screen/d0c37949-f384-4a14-ad34-011d39ef62ba/specs/)
* [Spacing](https://xd.adobe.com/view/fd6e4dde-2ecf-480a-aaaf-f5043cb04bf0-a83d/screen/81871b64-ce35-43bd-9bec-470dc4f10527/specs/) 
* [Links](https://xd.adobe.com/view/fd6e4dde-2ecf-480a-aaaf-f5043cb04bf0-a83d/screen/bb4191f2-d9c6-4ba0-b00d-30349108ab7b/specs/) scroll down to cta links for typography I used for 'inline links'

## Acceptance Criteria

- AC1 Package cx-elements contains typography as defined in the Brand.com design specs.
- AC2 Package cx-editors contains EditorPlain withAutoSuperscript as option.
- AC3 Package cx-editors container RichTextEditor that setups using the typography form AC1.
-- Editor should contain: Bold, Underline, Superscript, H1-H5, Link
- AC3 Package cx-flowcontainer contains the FlowContainer tokens for nesting and constraints.
- AC4 Typography, EditorPlain, RichTextEditor
- is in the cx-starter package 
- is activated on a styleguide pages within the Cxstarter Test Site
- and provide 'rest' type token example as well on component page.

## Notes
* **Scale provided is 18 but base font is 16 so REM created on base font to not override body html.**.  This should produce the same pixel size if calc done correctly.
* Suggest to not extend fontSize but override in tailwind config file in the package to purposely not allow text-4xl, etc to be used.
* Font is https://fonts.google.com/specimen/DM+Sans with weight defined (bold = 700, medium = 500, regular = 400.)
* Transform to uppercase in scope
* Site breakpoints are still be defined.  so when the **typography breaks at specific points it out of scope** -- just assume you see 'mobile' typography on something smaller than 1024 and desktop typography above 1024.  (currently tailwind's breakpoints for lg) 
* Colors in scope

**Comment by HalinaL** [comment]
Closed as completed
