### ISSUE TITLE
Documentation Copyright should 2022

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#1405]
## Description

Documentation Copyright should 2022

### Steps to reproduce

1. visit doc 
2. observe footer
3. 
### Expected result
Copyright 2019-22

### Actual result
Copyright 2019-20

Challenge that you turn the year into script that auto-updates each year.
File copyright is in: https://github.com/johnsonandjohnson/Bodiless-JS/blob/main/packages/bodiless-documentation/resources/index.html

**Comment by misterjones** [comment]
**Fix added in:** PR #1410 > commit db905b1
