### ISSUE TITLE
isEdit parameter is missing in session storage after the bodiless page is opened 

### ISSUE THREAD

**Issue by pomi** [johnsonandjohnson/Bodiless-JS#1473]
## Description

isEdit parameter is missing in session storage after the bodiless page is opened 

### Steps to reproduce

Open bodiless site
Open dev tools -> Session storage -> Bodiless url
Check for isEdit parameter

### Expected result

isEdit parameter is set to false

### Actual result

isEdit parameter is missing

### Environment

 System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.3

### Affected Version

commit 242d1fe93876097a139ac07df63a37de612ccdbe (HEAD -> main, origin/main, origin/HEAD)
Author: wodenx <coden@its.jnj.com>
Date:   Tue Mar 8 13:34:29 2022 -0500

    chore(*): Upgrade Dependencies and Refactor (#1395)
    
    * Generic store moved to bodiless core

**Comment by HalinaL** [comment]
It was decided to close this issue because the workaround was found
