### ISSUE TITLE
Starter: there are layout issues on /styleguide/layout/ and /styleguide/header/ pages

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#1480]
this is a gap from  #1465

*STR:*
1. open /styleguide/layout/ on Edit or on Static env Starter Site
*AR:*
the layout differs from the previous version
_before:_
![Screen Shot 2022-03-18 at 4 44 18 PM](https://user-images.githubusercontent.com/3224040/159767772-7be18944-3f9e-45c9-b1be-77cdfa341417.png)

_after:_
![Screen Shot 2022-03-23 at 12 45 11 PM](https://user-images.githubusercontent.com/3224040/159767850-442a0ce4-8bf8-4c27-a53e-778fce27a2c8.png)

 

1. open /styleguide/header/ on Edit or on Static env Starter Site
*AR:*
the layout differs from the previous version
_before:_
![Screen Shot 2022-03-22 at 5 50 17 PM](https://user-images.githubusercontent.com/3224040/159768277-51b41790-11f6-469d-abac-6b1f0c058950.png)

_after:_
![Screen Shot 2022-03-23 at 12 44 05 PM](https://user-images.githubusercontent.com/3224040/159768313-a6f2aa40-b80d-43ae-a3e5-088333c2646f.png)

*ER:*
!!to confirm

**Comment by hvanyo** [comment]
Layout should have been addressed in generic template.
Header is ok that it follows the description.

**Comment by TatsianaMiraniuk** [comment]
the pages look as expected.
