### ISSUE TITLE
Token object altered after applied with asTokenSpec type improvement

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1496]
## Description

Token definition changed after applied in asTokenSpec.

### Steps to reproduce

- create some token spec with overlap domains, i.e
```javascript
const TokenDefault = {
    Core: {},
    Schema: {
       _: () => true,
    },
};
const TokenMore = {
  Core: {},
  Schema: {
      _: 'classes ...',
  },
};
```

- apply asTokenSpec(TokenDefault, TokenMore, ...)
- check TokenDefault

### Expected result

TokenDefault has no change.

### Actual result

TokenDefault.Schema changed

**Comment by wodenx** [comment]
Fixed in scope of #1525
