### ISSUE TITLE
Refactor the RichText API

### ISSUE THREAD

**Issue by beliayeu** [johnsonandjohnson/Bodiless-JS#15]
## User Story

- AS A site builder
- I WANT to create new RichText Components using the same Design System used to create other @bodiless Components
- SO THAT I have a consistent Interface

### Background/Description

Example: 
{code:java}
const simpleDesign = {
SuperScript: asSuperScript,
};
const basicDesign = {
Bold: asBold,
Italic: asItalic,
Underline: asUnderline,
Link: flow(asEditableLink(), asLink),
...simpleDesign,
RedText: addClasses('text-red-500'),
AlignLeft: asAlignLeft,
AlignRight: asAlignRight,
AlignJustify: asAlignJustify,
AlignCenter: asAlignCenter,
};
const fullFeaturedDesign = {
...basicDesign,
H1: asHeader1,
H2: asHeader2,
H3: asHeader3,
};

const EditorSimple = withDesign(simpleDesign)(RichText);
const EditorBasic = withDesign(basicDesign)(RichText);
const EditorFullFeatured = withDesign(fullFeaturedDesign)(RichText);{code}

### Acceptance Criteria

AC1:  The RichText Component takes a design prop that lets me use @bodiless design API to inject component to be used in the richText

AC2:  I should be able to add HOC to the design to set richText component properties such as

Type (block mark or inline) (e.g. asBlock, asInline, asMark)
Button to use (withButton('icon'))
shortcut key (withShortcutKey('k')
if it is Void or not (asVoid)
 

AC3: for the following component if they are included in the Design then default settings should be used as well as a default component (the default should be what we currently use)

- Bold
- Italic
- Underline
- Link
- SuperScript
- AlignLeft
- AlignRight
- AlignJustify
- AlignCenter
- H1
- H2
- H3
AC4: The documentation for using the API is updated

 

AC4: There are unit test for all of the helper functions 

 

AC5: The following items should be added at the site level to the FullFeatureEditor

- Strike through withButon('strikethrough_s'), withShortcutKey('s'), asMark, asStrikethrough
- Quote block   startWith(Div), withButton('format_quote'), asBlock, asBlockQuote,

**Comment by e2thex** [comment]
fixed by #18
