### ISSUE TITLE
Add selectors to containers on flow container page

### ISSUE THREAD

**Issue by pomi** [johnsonandjohnson/Bodiless-JS#1510]
Description
Add selectors or any other specific attribute to flow container elements (containers)

Steps to reproduce
Open Flow Containers page
Switch to edit mode
Check containers elements

Expected result
There is no distinctive way to select any present container

Actual result
aria-label=ContainerName would be great

Environment
System:
OS: macOS 12.2.1
CPU: (10) arm64 Apple M1 Pro
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.13.2 - /usr/local/bin/node
npm: 8.1.2 - /usr/local/bin/npm
Languages:
Python: 2.7.18 - /usr/bin/python
Browsers:
Chrome: 99.0.4844.74
Safari: 15.3

Affected Version

commit 22384f184e73366bc00ec619e7b08fa3e5dfc29d (origin/main, origin/HEAD, main)
Author: Lucas Varela <lvarelab@its.jnj.com>
Date:   Mon Mar 21 13:30:11 2022 -0300

    feat: Add static replacement mechanism (#1440)
    
    * Add a mechanism to prevent component hydration

**Comment by HalinaL** [comment]
Closed as completed
