### ISSUE TITLE
Public Demo Site

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#1523]
## User Story
As a prospective site builder
I want a public site demonstrating key Bodiless features
So that I can learn how amazing Bodiless really is

## ACs
There is a public demo site deployed to p.sh and netlify which showcases the following features:
- Sitewide data in header/footer
- Rich text editing
- Plain text editing
- Gatsby image
- Flow container
- List editing
- Navigation (cx-navigation)
- Content library

Publicly available site should not allow saving content (BODILESS_BACKEND_SAVE_ENABLED="0") -- this requires #1522

**Comment by kbray0009** [comment]
Hey I have created a new card.

https://6o2fc3.axshare.com/#id=y2wl2m&p=fake_brand_site&g=1

**Comment by kbray0009** [comment]
Table design

https://dbzu8p.axshare.com/#id=pobau4&p=page_1&g=1

**Comment by hvanyo** [comment]
Closing as we don't need this issue and site will live at https://github.com/wodenx/bodiless-demo
