### ISSUE TITLE
Migrate Cypress to Playwright

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#1526]
## Description
As a developer I want Playwright integration running in CI and all tests executing in playwright, so I continue to have test automation coverage.

Technical notes:
* Stretch that would be nice:  is on activation that Playwright is only installed as needed during the test phase and not all the time.  Potentially in our CI pipeline.
* Cypress is left as is for now and will be removed.   Toggle between Playwright & Cypress.  Potentially an env variable.

Estimation is approximately 4 days to migrate existing tests.

PR - https://github.com/johnsonandjohnson/Bodiless-JS/pull/1487
## Acceptance Criteria
All cypress tests are rewritten and executing in playwright.
Playwright CI is actively executing on every PR on Bodiless by default.
Ability to provide a way to run either Playwright & Cypress tests.

**Comment by hvanyo** [comment]
Address with https://github.com/johnsonandjohnson/Bodiless-JS/pull/1487
