### ISSUE TITLE
Warning: Invalid prop `name` supplied to `React.Fragment`. ...

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#1532]
## Description
STR
- Checkout master branch
- `npm run setup && npm run start`
- open http://localhost:8005/

Expect:
- Console has no warning

Actual
- Warning: Invalid prop `name` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

 

Notes:
- Possible causing: https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-core/src/ContextMenu/StructuredChildren.tsx#L22
- Default GroupComponent as React fragment taking `name` prop.

**Comment by hvanyo** [comment]
Addressed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/1530
