### ISSUE TITLE
There is a runtime error when clicking Logo after opening Email on /social-share/

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#1601]
### Steps to reproduce

STR:
1. open /social-share/ in Edit Env in Review Mode Test Site
2. click any Share button
3. click Email button
4. click Logo in Header

### Expected result

no errors, Home page opens

### Actual result

there is a runtime error, several errors in a browser console

### NOTEs:
1. not reproduced if FB or Twitter icons are clicked instead of Email
2. not reproduced if any link from Menu is clicked instead of Logo
3. not reproduced if Breadcrumbs links are clicked instead of Logo
4. not reproduced if the URL is changed to http://localhost:8005/ directly in a browser URL field
5. no issue on Static env

**Comment by TatsianaMiraniuk** [comment]
that was a bug in Update dep. branch, and not Main yet. It's been fixed.
