### ISSUE TITLE
Highlighting Link in Tout replaced it with actual href link

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#161]
## Description

If you try highlight a linked tout cta, it replaces it with the actual href link

### Steps to reproduce

1. place a tout and link the cta and name the cta link (or use existing tout that has linked CTA)
2. highlight the CTA link (to copy it elsewhere)

### Expected result

Highlights as expected

### Actual result

Highlighting injects the href value into the text cta title.
https://www.screencast.com/t/qbmrsFj4f8Su

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

0.0.40
https://github.com/johnsonandjohnson/Bodiless-JS/commit/a838b1042407045be9433579b43b680ca612c280

**Comment by schristodoulou** [comment]
This issue also came up in usability testing.

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/306
