### ISSUE TITLE
List has as many items inside "Insert Component" as were added into added List component, when we start new adding from flow container paddings.

### ISSUE THREAD

**Issue by ValeryRudko** [johnsonandjohnson/Bodiless-JS#1651]
Steps to reproduce:
1. Setup either test-site or vital-demo;
2. Go to any page with flow container available;
3.  Add "List" item;
4. Add several items inside the list;
5. Click inside the paddings of flow container to open Component adding menu without List menu 
![image](https://user-images.githubusercontent.com/39922356/165517101-2d651bad-6e72-4758-8827-366bb0e4462a.png)
6. Select Add option and go to List adding

Actual result:
List item is presented for adding with so many items inside, as many were added to item in flow container
![image](https://user-images.githubusercontent.com/39922356/165517541-5203b080-680d-4a47-8526-b0b7cbcb1883.png)

Expected result:
One item is expected to be presented for adding:
![image](https://user-images.githubusercontent.com/39922356/165517668-c0ab80b2-2d22-41e6-8562-e4e0ee1155bb.png)

**Comment by HalinaL** [comment]
It was decided to leave this behavior as is
