### ISSUE TITLE
Default RTE - a link text size doesn't match to H1-H4 sizes (Vital Demo)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#1654]
**Steps to reproduce:**
 1. on Vital Demo, open any page with default RTE component or /styleguide/editors/ page in Edit env, Edit mode
 2. in default RTE add some text
 3. highlight any word to get Style Menu
 4. set H1
 5. highlight any word and set a link

**Actual Result:**
 a linked text size is smaller than a corresponding H1-4 style

![Screen Shot 2022-04-27 at 12 30 02 PM](https://user-images.githubusercontent.com/3224040/165567829-b52b3a50-cbfa-4324-a5b8-811375ba2274.png)

**Expected Results:**
Linked Text has the same font size as H1-H4

**Comment by hvanyo** [comment]
Addressed in https://github.com/johnsonandjohnson/Bodiless-JS/pull/1781
