### ISSUE TITLE
Warning message during migrated site build: warn Module not found: Error: Can't resolve './src/no-scroll-settings.json'

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#167]
### Steps to reproduce

Within Mono repo

1. `cd examples/starter`
2. `# setup migration-settings.json`
3. `npm run migrate`
4. `npm run build`

Within New site

1. git clone https://github.com/johnsonandjohnson/bodiless-js.git
2. cd bodiless-js
3. npm ci
4. npm run new ../migratesite
5. cd ../migratesite
6. npm install (fix and add morgan dependencies issue that came in 0.0.40)
7. update migration_settings.json and use scroll feature (https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-migration-tool/doc/Technical/MigrationTool.md#configure-no-scroll-for-selected-anchor-element)
8. npm run migrate

### Expected result

no warning

### Actual result

with warning message:
_warn Module not found: Error: Can't resolve './src/no-scroll-settings.json' in '/path/to/bodiless-js/examples/starter'_

**Comment by asiarheyeu** [comment]
Bugscrub notes:
- Not checked if no-scroll-settings works as expected. It's better to fix this issue and verify afterwards
- To test outside of monorepo by developer
- Product owner to prioritize accordingly
