### ISSUE TITLE
Link form doesn't open in Flexbox area for RTE. Url cannot be added.

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#168]
## Description
Link form doesn't open in Flexbox area in RichText Editor. Url cannot be added.

### Steps to reproduce
1. open /flexbox/
2. add a tout with a body, e.g. first one in the Picker
3. type a few words in Tout body
4. highlight some word and select a link style -> the word changes to a link style (expected) 
5. click on the word to set a url value
### Expected result
Link form opens
### Actual result
Link form doesn't open. url cannot be added.

### NOTEs:
1. same issue reproduced for any component (with RTE) placed in /flexbox 
2. same reproduced for any flexbox area in the test site; e.g. in /richtext/ - Link form doesn't open in Flexbox, but works well in RTE on the page
3. Link form works as expected in /touts/, /accordion/, /gallery-final/, /richtext/, and other on non-flexbox area
4. the issue is not reproduced for Image, CTA link in Tout

### Environment
 System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 11.1
  npmGlobalPackages:
    gatsby-cli: 2.8.29

### Affected Version
introduced by [8148e1c6201d3ec64fcaf089076c4a37d3fa5923](https://github.com/johnsonandjohnson/Bodiless-JS/commit/8148e1c6201d3ec64fcaf089076c4a37d3fa5923)

**Comment by asiarheyeu** [comment]
Bug scrum notes:
- To check is it reproducible for CTA as well
