### ISSUE TITLE
Provide default psh cache expiry and allow local override

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#172]
## User Story

AS A Site Builder
I WANT the caching setting enable by default with platform default of 6 hours
SO THAT I quickly enable CDN and not have to set this per site.

As A Site Builder
I want to be able to customize cache expiry for my site
So that I can meet business requirements.

As a Platform Maintainer
I want to be able to roll out changes to p.sh configuration globally
So that I can improve deployments for all

### Background/Description

Fastly caching requires  "expires" setting on .platform.app.yaml  

### Acceptance Criteria

AC1:
The .platform.app.yaml files which are written by bodiless-psh-init
Are created by merging specific whitelisted keys in the site’s (.platform.app.yaml & `edit` `*.platform.app.yaml`)
And global version from @bodiless/psh (packages/bodiless-psh/resources/static/static.platform.app.yaml & packages/bodiless-psh/resources/edit/edit.platform.app.yaml

AC2.
The merge should use a recursive algorithm
to ensure that individual keys of nested objects are preserved (eg lodash `merge`).

AC3.
There is a whitelist of keys maintained in @bodiless/psh
And only whitelisted keys will be merged.

AC4.
Non-whitelisted keys will be ignored,
And a warning message will be printed to the console.

AC5.
All files created by `bodiless-psh-init` are overwritten by default
Every time you run `bodiless-psh-init`.
(opposite of current behavior, in which you must specify an `--override` switch).

AC6
The default `static.platform.app.yaml` has a default cache expiration
For the `/` and `/___docs` added.

AC7.
Documentation is updated with overview of merge & update doc of any necessary changes.

### Implementation Notes

Needs to be tested on platform.sh and verify the expires value is set in the platform app YAML file. 
Any site can override the expires to meet their requirements.

### References

https://docs.platform.sh/configuration/app/web.html#locations

**Comment by hvanyo** [comment]
@VancheeZze  implemented simpler version of AC1 which is 
The .platform.app.yaml files which are written by bodiless-psh-init
Are created by merging specific whitelisted keys in the site’s (static.platform.app.yaml)
And global version from @bodiless/psh (static.platform.app.yaml)

If we are all in agreement, lets update this AC1 to reflect this.

cc: @dewen  @wodenx  @schristodoulou

**Comment by hvanyo** [comment]
@VancheeZze  says that AC7 has technical imlementation

> AC7 Is not implemented. There were some problems with the package been "installed" on "npm run bootstrap" and "npm run setup" in monorepo and some other cases when "postinstall" hook has been triggered and we decided to remove it for now 

Suggest removing AC7

cc; @dewen  @wodenx  @schristodoulou

**Comment by VancheeZze** [comment]
@hvanyo Yeh, I'd do that too. Let's change AC7 to update documentation.

**Comment by hvanyo** [comment]
@VancheeZze  @dewen  @wodenx 
Is merging of Edit files in scope here or only this one specific file?  @VancheeZze  says .edit is implemented and simple.
