### ISSUE TITLE
Docs loses top menu if not on home docs page

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#173]
## Description

Docs loses the top menu when you browse documentation and leave the home page

### Steps to reproduce

1. bring up docs
2. browse to any non-home page

### Expected result
See top menu

### Actual result
No top menu
What happened.

### Environment

local & platform.sh.

### Affected Version

0.0.40

**Comment by asiarheyeu** [comment]
Bugscrub notes:
- To be discussed on documentation pre-grooming meeting by POBA team

**Comment by dewen** [comment]
Causing of the issue is missing _navbar.md from doc sub-folders. Unlike _sidebar.md, which is created for each sub-folder, _navbar is unique across the site, so the work around is to apply an alias redirect to root _navbar.md.
