### ISSUE TITLE
Adding sub-menu removes main menu link

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#1919]
STR
On Vital Demo
1. Add a link to a main menu item which does not have a sub menu
2. Add a sub-menu

ER
1 Clicking on main menu shows Menu=Link buttons
2 Main menu item still has link

AR
1.  Only "Add" and "Delete" buttons appear
2. Min menu item link is removed.

**Comment by hvanyo** [comment]
This is default behavior of Vital Menu -> 
https://edit.main-bvxea6i-vadijmmtl4ax4.us-4.platformsh.site/___docs/#/VitalDesignSystem/Components/VitalNavigation/Menu?id=add-a-menu-link
