### ISSUE TITLE
Local Context Menu of List component without a link is visible and functions in Preview Mode

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#196]
## Description
Local Context Menu of List component without a link is visible and functions in Preview Mode

### Steps to reproduce
1. open /list/ page
2. click an item in a List without a link functionality (located at the left) -> Local Menu with the icons is shown
3. Switch to Preview Mode (click Edit button in Editor Menu)

### Expected result
Local Context Menu is hidden

### Actual result
Local Context Menu is still visible and functions
![Screen Shot 2020-03-04 at 10 55 51 AM](https://user-images.githubusercontent.com/3224040/75898083-940ec780-5e07-11ea-8606-0277a1f71ee8.png)

### Environment

System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 11.1
  npmGlobalPackages:
    gatsby-cli: 2.8.29

### Affected Version

reproduced in Master

**Comment by asiarheyeu** [comment]
Per bug scrub
- Context Menu stories are on the roadmap and will be implemented by the Core Team later. It may be not worth to address it now
- PO to prioritize the item accordingly

**Comment by asiarheyeu** [comment]
Closing as fixed
