### ISSUE TITLE
Module not found: Error: Can't resolve 'mobx-react' in ...

### ISSUE THREAD

**Issue by xingBaGan** [johnsonandjohnson/Bodiless-JS#1977]
## Description
![image](https://user-images.githubusercontent.com/53329437/216749474-8becf687-82b1-4a84-9674-c150ed16c994.png)

ModuleNotFoundError: Module not found: Error: Can't resolve 'mobx-react' in 'E:\bodiless_wrokspace\demo6\sites\startup\node_modules\@bodiless\gatsby-theme-bodiless\dist'
### Steps to reproduce

After running the  ` npx @bodiless/cli@next new -r head` and
![image](https://user-images.githubusercontent.com/53329437/216749551-55e8cee7-6c03-4754-9e7b-c92e5b52736a.png)

### Expected result
Start the project successfully.

### Actual result

What happened.

### Environment

 System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.10.0 - D:\nodejs\node.EXE
    Yarn: 1.22.10 - D:\node.js\node_global\yarn.CMD
    npm: 7.24.0 - D:\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Chrome: 109.0.5414.120
    Edge: Spartan (44.18362.1533.0)
  npmPackages:
    gatsby: ^4.11.2 => 4.25.4
    gatsby-plugin-gatsby-cloud: 4.13.0 => 4.13.0

**Comment by dewen** [comment]
@xingBaGan seems the `next` prerelease build failed, we are trying to fix.

Meanwhile, please try with previous rc release:
```
npx @bodiless/cli@next new -r v1.0.0-rc.22

# follow the prompt to specify the site directory and site name
cd [new site]

# add git remote origin (so the backend can work as expected)
git remote add origin [remote git repo url]

# start dev mode
npm run start
```

Regards

**Comment by dewen** [comment]
@xingBaGan 

`npx @bodiless/cli@next new -r head` issue should be resolved after last prerelease. Please confirm and I will close this issue. Thanks
