### ISSUE TITLE
Filterable item metadata

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#222]
## User Story
As a content editor
I want to be able to add metadata (tags) to a component
So that I can allow an end user to hide it with a filter.

## Acceptance Criteria
AC1.
Any component can be wrapped (with one or more other components or HOCs) so that it provides an interface (form) for adding and removing tags. (see the wireframes "Groups" tag)

AC1a. There is a way to view All Groups (see example in wireframes "View All Groups" link). 

AC2.
The tags so added are stored as content (json files).

AC3.
The set of available tags can be constrained by the site builder when wrapping the component.

AC4
One can add a term that is not in the constrained list

AC5.
There is another wrapper which accepts a prop that is a function that takes tags
The component should call this function to pass its tags, if it returns false it should not show,
eg:
```
const myCallback = (tags: string[)) => logicThatDeterminesIfItShouldShow ? true : false;

<WrappedComponent shouldShow={myCallback} />
```

AC6.  
There exists a third wrapper which can wrap the above component
which causes it to show if it contains all of the tags passed as a prop, eg
```
<WrappedComponent tags={["foo", "bar"]} />
```
will render if the wrapped component has both foo and bar

AC7.
There is a page on the test site that includes a component wrapped (AC1-A6) for filtering. 
Along with allowing user to switch which tags should be used for filtering as well as multiple tag filters (foo + bar) 
(inputs to AC6).

## Implementation Notes:
- See wireframes https://jhdfdc.axshare.com/#g=1&p=product_lising&id=0sjqur 
- Unit Tests are also in scope. 
- The form autocompletes, so if the user enters an existing tag it will fill it in for them. 
- Validation requirements will be another story

**Comment by e2thex** [comment]
we are thinking about https://www.npmjs.com/package/react-tag-autocomplete#addonblur-optional

**Comment by wodenx** [comment]
@awm086 
I see this as a set of (probably) 3 HOC's which can be used to add this functionality. 
- The first would be responsible for adding the menu button (probably to the local context menu, but need to verify this with kevin), similar to the [toggle button HOC](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-components/src/Toggle.tsx#L56).  Clicking the button would bring up a form, and the form would have our tagging control as a field (Erik linked the library we found above, but you should do some research to see if there are any alternative libraries we should consider).  You can use the existing `withEditButton` hoc as is done in List(https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-components/src/Link.tsx#L100), but you'll need to [wire the tagging control into the informed data structure](https://joepuzzo.github.io/informed/?path=/story/custominputs--creating-custom-inputs). Your HOC would also need to add a prop to the wrapped component which accepts the list of available tags (used to provide autocomplete suggestions for the tagging control).  It would also define data handlers  to save/read the tags to a json file.  These should be separate from the HOC itself so they can be used by other consumers -- a good pattern is to extract them to a reusable react hook.  Again [Toggle `useAccesors`](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-components/src/Toggle.tsx#L25-L33) is a good example.

Start by working on the above (which should cover AC's 1-4.  Post questions if you have them and i'll try to answer later.  Will post comments on the other AC's later tonight or tomorrow morning.

**Comment by wodenx** [comment]
In the simplest form, the remaining AC's could be implemented this way:
- A simple wrapper which uses the data accessors from above to read the item's tags, passes them to a callback function, and shows or hides itself if the function returns true/false - eg:
```
type FilterFunc = (tags: string[]) => boolean;
type FilterByTagsProps = {
  filter: FilterFunc,
};
const withFilterByTags = <P extends object>(Componen: ComponentType<P>) => ({ filter, ...rest }: P & FilterByTagsProps => {
  const tags: string[] = useAccessors().getTags();
  return filter(tags) ? <Component {...rest} /> : <Fragment />;
}
```
- An implementation of the above which produces a component accepting as another prop a set of "selected tags", and uses a filter function which shows the component if
- the selected tags set is empty
 - the item tags contain *all* the selected tags
eg
```
const getFilterFunc = (selectedTags: string[]) => (itemTags: string[])=> (
  selectedTags.length === 0 || itemTags.containsAll(selectedTags); // implement or find utility for containsAll()
);
const withFilterBySelectedTags =<P extends object>( Component : ComponentType<P & WithFilterBySelectedTagsProps>) => {
  const FilterableComponent = withFilterByTags(Component);
  return (
    props => {
      const { selectedTags, ...rest } = props;
      const filter = getFilterFunc(selectedTags);
      return <FilterableComponent filter={filter} {...rest} />;
    }
  );
}
```

(NOTE: The above code is just sketched - it probably has errors)

**Comment by wodenx** [comment]
Another pattern to manage the actual filtering is demonstrated [here](https://github.com/wodenx/Bodiless-JS/blob/direction/filter-item/packages/bodiless-components/src/filterHOC.tsx) cc @e2thex
