### ISSUE TITLE
Migrate page and resource redirections

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#226]
## User Story

As a site flattener tool operator
I want to migrate page and resource redirections
So that I can preserve existing site behavior

### Acceptance Criteria

AC1
when migration tool hits pageA that is redirected to pageB
then the redirection is written to a yaml file

AC2
when migration tool hits pageA that is redirected to pageB
then the redirection is logged to the terminal

AC3
when migration tool hits pageA that is redirected to pageB
then pageA is not created
then pageB is created

AC4
when migration tool hits pageA that is redirected to pageB hat is redirected to pageC, etc (pageA -> pageB -> pageC -> ... -> pageN)
then pageA, pageB ... pageN-1 are not created
then pageN is created if the server responded with Success status

AC5
when migration tool hits resourceA (image, style, script, etc) that is redirected to resourceB by the server
then the redirection is written to .platform/routes.yaml according to psh doc

AC6
when migration tool hits resourceA (image, style, script, etc) that is redirected to resourceB by the server
then the redirection is logged to the terminal

AC7
when migration tool hits resourceA (image, style, script, etc) that is redirected to resourceB by the server
then resourceeA is not created
then resourceB is created

AC8
when migration tool hits resourceA that is redirected to resourceB that is redirected to resourceN, etc (resourceA -> resourceB -> resourceC -> ... -> resourceN)
then resourceA, resourceB ... resourceN-1 are not created
then resourceN is created if the server responded with Success status

AC9
unit tests created

AC10
documentation is updated how to include results from AC1 to psh routes

**Comment by hvanyo** [comment]
@dewen  @beliayeu  @schristodoulou  @TatsianaMiraniuk 
The downloading of resources is being done in two ways.  
This solution above is being implemented on the first method.
If the resources are attempted to be downloaded and found missing in the second method, they will not be redirected with this solution.  We will put these gaps tickets to determine amount of cases and if we should add this solution to second method.    i.e. srcset in pictures
@dewen  @beliayeu  @TatsianaMiraniuk  -- Tanya will probably need help to determine if we are following into the second case and missed  OR its the first case and not working.
