### ISSUE TITLE
[GAP] Define Design for the Flexbox 

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#234]
## User Story

AS A Site Builder
I WANT the ability to add component level styling to the flexbox
SO THAT I can have margins and padding that fit my designs.

### Background/Description

In https://github.com/johnsonandjohnson/Bodiless-JS/issues/213 we defined the design standard for the Flexbox, we need to update the flexbox margin to -20px

### Acceptance Criteria

AC1. On the test site, anywhere the flexbox component is in use should have a margin of 20px and the flexbox itself has a -20px margin.

### Implementation Notes

see example https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items#Creating_gutters_between_items

**Comment by hvanyo** [comment]
Dup of https://github.com/johnsonandjohnson/Bodiless-JS/issues/235
