### ISSUE TITLE
/products page: a product tout doesn't take 1/4 width(Edit env)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#243]
## Description
/products page: a product tout doesn't take 1/4 width (Edit env)

### Steps to reproduce
1. open /products page in Edit env.
2. in the bottom flexbox add a product tout
### Actual result
a tout shows much wider than expected. [resizing is not allowed here - existing behavior]
![Screen Shot 2020-03-26 at 6 14 21 PM](https://user-images.githubusercontent.com/3224040/77701900-a9ea5500-6f8d-11ea-9e2a-6cc906bf83ea.png)

### Expected result
a tout takes 1/4 width

3. Switch to Static mode
### Expected/Actual result
a tout takes 1/4 width
![Screen Shot 2020-03-26 at 6 14 25 PM](https://user-images.githubusercontent.com/3224040/77701911-afe03600-6f8d-11ea-8e7d-dab11f9821e9.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 80.0.3987.149
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/9ee52e39741004d263a5c06055520b197947f942)

**Comment by schristodoulou** [comment]
Issue appears to be resolved.
