### ISSUE TITLE
New Page: a trailing slash is missed in a url of a newly created page (Edit env)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#251]
## Description 

a trailing slash is missed for a newly created page (Edit env)

### Steps to reproduce
1. open /products/  page in Edit env and switch to Edit mode
2. create a new page (click '+ Page' in Editor Menu)
3. enter a page path, e.g 'pdp-test'.  
4. click 'v'
### Expected result
a  'pdp-test' page with a trailing slash in the url is expected - ../products/pdp-test/

### Actual result
a 'pdp-test' page is created but without a trailing slash - ..products/pdp-test
![Screen Shot 2020-03-31 at 5 04 07 PM](https://user-images.githubusercontent.com/3224040/78075052-d0373880-7371-11ea-9b4b-a707974065a9.png)

Note:
redirection to a trailing slash version path does not happen in Edit env until  'npm run build' is executed and Edit env is restarted 

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 80.0.3987.149
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/6729765d3a543b11e2bc9cc4be537d3f7aa0dfc5)

**Comment by asiarheyeu** [comment]
Closing as won't fix due to low priority. Static app is not affected by this issue
