### ISSUE TITLE
Filters Should be Open by Default in the Component Picker

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#264]
## User Story

- AS A Content Editor
- I WANT to filter the list of available components 
- SO THAT I can see the full list of options

### Background/Description

Most users did not notice the filters

### Acceptance Criteria

AC1: The list of filters in the component picker are open by default. 
AC2: Most common components are surfaced to the top
- Type:
- Rich Text Editor
- Images
- Touts
- Contentful 
- Single Accordion

### References
![Canvas_X_Investigation_pptx](https://user-images.githubusercontent.com/59970745/78673651-70301d00-78b0-11ea-9b31-a72540ca72b5.jpg)

**Comment by hvanyo** [comment]
Shouldn't we add order as well here.   That was important as well.
