### ISSUE TITLE
Add Image Component

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#265]
## User Story

- AS A Content Editor
- I WANT to add an Image to my page
- SO THAT I can follow the Brand's design

### Background/Description

- Users wanted an Image component and not just TACOs
- Users should not be confused by dimensions 
- We need to complete the UI abstraction API (at least iteration 1) and then use it in image component.

https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-components/src/Image.tsx#L115

### Acceptance Criteria

AC0: There is a landscape and square version of AC1 and AC2.  **updated landscape was previous horizontal 5/14/2020 with the following titles/descriptions:
Title: Square Image. Description: Adds a square image
Title: Square Linkable Image. Description: Adds a square linkable image
Title: Landscape Image. Description: Adds a landscape image
Title: Landscape Linkable Image. Description: Adds a landscape linkable image

AC1: There is an Image components (with all variations) in the Component Picker on examples/test_site.

AC2: The image component (and new default placeholders is used in the header image in the examples/starter_kit.  (uses the Landscape Image) 

AC3: Image default placeholders uses attached color image.  Image: https://user-images.githubusercontent.com/1383878/79777104-c1a2c800-8304-11ea-8972-2897071e52b1.png

AC4: All Images on examples/test_site & starter_kit use the default Image placeholder if they haven't overwritten the image (ie. TACO images have been replaced with the new image placeholder unless there is .json file assigning)   

AC5: Image upload supports JPG, PNG, GIF, SVG, WebP, APNG

AC6: Default placeholder can be overridden for an Image Component.

AC7: Remove use cases in the Examples/Test site where header image was overwritten (see use cases below) Image: https://user-images.githubusercontent.com/1383878/79788152-2ca8ca80-8316-11ea-9ba0-da6060dedc71.png

AC8: There is test page on examples/test_site with test identifiers to demonstrate Image Components in AC1 & AC2 with all supported image types and overriding default image.

AC9: 
All UI elements for the bodiless-components package
Are injectable via a ui prop on the Image component.
Image elements (ie. form) work as expected.

### Implementation Notes

Image Types:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types

Use cases where default image was used:
https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/examples/test-site/src/components/ProductListing/index.tsx#L41-L51

### References
![Banners_and_Alerts_and_Canvas_X_Investigation_pptx](https://user-images.githubusercontent.com/59970745/78674359-7b377d00-78b1-11ea-8829-b5a03ff6ae51.jpg)

**Comment by kbray0009** [comment]
Hey you can use the image we were using on the demo site.
![blue-dark](https://user-images.githubusercontent.com/1383878/79124831-268d7980-7d6b-11ea-9eaa-1f2077047743.png)
