### ISSUE TITLE
Activate GTM on a Flattened Site that did not have GTM

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#266]
## User Story

As a Brand flattening a site
I want to be able to add GTM to my site
So that my site metrics can be collected. 

### Acceptance Criteria

AC. There is documentation of issues/gaps to review regarding a flattened site that wants to add GTM

### Implementation Notes

Task:

- Flatten a site that does not have GTM on it
- Activate Bodiless GTM
- Perform testing
- Record any issues/gaps

Documentation:

**Comment by hvanyo** [comment]
@schristodoulou  we should remove this.  we don't expect to have code chagnes to bodilessjs and documentation updates is proprietary.
