### ISSUE TITLE
Admin SubMenu 

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#277]
## User Story

- AS A Content Editor
- I WANT submenus 
- SO THAT left admin isn't cluttered and functionality is grouped 

### Acceptance Criteria

AC1.
GIVEN the user is on the edit UI
Then there is a "File" icon on the main menu

AC2.
When the user clicks on the "File" icon 
THEN there is a panel window with a Title and the icon options for Pull, Push, History, Revert (correct order & names)
AND the sub menu panel window includes the "x" icon for closing the window
AND does not include the checkmark icon for accepting interaction. 

AC3.
WHEN the user clicks on the Pull, Push, Revert, History or close icons from the panel window (sub menu)
THEN existing functionality behaves as expected.

AC4. 
Submenu content opens in the same panel window
AND
Closing a submenu items returns back to the parent item(s)

AC5. 
Automated tests are updated to reflect above criteria. 

AC6. 
The "sub menu" in the Page Panel window, that allows for a selection between different functional options, is a reusable component

### Implementation Notes

- Scope of this story includes have a main menu icon that opens a sub menu of existing icons
- The Changeset text is not in this scope and will be part of another story

### References

- Wireframes: https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9
- Relates to Clone Existing Page #70
![Aries](https://user-images.githubusercontent.com/59970745/83162523-dc244a00-a0d7-11ea-923f-c707c158132f.jpg)

**Comment by schristodoulou** [comment]
Scope of this ticket is only 1-level of submenus.
