### ISSUE TITLE
Can't add custom GTM events for migrated site that had no GTM

### ISSUE THREAD

**Issue by VancheeZze** [johnsonandjohnson/Bodiless-JS#278]
## Description
When a site that had no GTM is migrated, adding GTM events causing build errors

### Steps to reproduce
- Migrate https://www.bebe.de/
- Activate GTM following instruction described here: https://sourcecode.jnj.com/projects/ASX-NBFP/repos/canvasx/browse/packages/canvasx-documentation/doc/Components/GTM/GTM.md
- Define new Helmet component:
```js
const ExampleGTMHelmetEvent = flowRight(
  asBodilessHelmet('datalayer'),
  withEvent(
    'digitalData',
    {
      event: 'Page Loaded',
      page: {
        country: 'US',
        language: 'EN',
        hostname: 'bodilessjs.com',
      },
    },
    'page-loaded',
  ),
)(Helmet);
``` 
- Add this Helment component to the page template or you site's global page template.

### Expected result

GTM event is added to the page and site builds with no errors.

### Actual result

There is a build error once we try to add `<ExampleGTMHelmetEvent />` to the page template.
<img width="450" alt="Screen Shot 2020-04-14 at 8 36 56 AM" src="https://user-images.githubusercontent.com/13271812/79333238-2c5e9880-7eec-11ea-899d-ec48a0ee8905.png">

<img width="450" alt="Screen Shot 2020-04-14 at 8 03 34 AM" src="https://user-images.githubusercontent.com/13271812/79333259-37b1c400-7eec-11ea-872c-3e50d9fbb2d7.png">

 

### Environment
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 67.0.4
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.17 => 2.19.17 
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.10.0
```

### Affected Version
- Reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/6729765d3a543b11e2bc9cc4be537d3f7aa0dfc5)

**Comment by hvanyo** [comment]
Closing as won't do.
