### ISSUE TITLE
Link to Coding Standards is broken

### ISSUE THREAD

**Issue by mereck** [johnsonandjohnson/Bodiless-JS#29]
## Description

The link to Coding Standards ( https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-documentation/doc/Development/Development/Release/Quality) in the *Raising Pull Requests* section is broken on https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-documentation/doc/Development/Contributing.md

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1095106/72277740-793a8680-3600-11ea-83e4-eb2e5d0baee4.png">

**Comment by wodenx** [comment]
@mereck It's a problem with using a docs builder - the link works if you view the guidelines in the docs app, but not from github.  I guess one solution would be to link directly to the coding standards on github pages.  Would be happy to have a PR for this. Thanks.

**Comment by gobinathm** [comment]
Just validated, the link seems to be working fine. Hence i believe this issue can be closed

https://user-images.githubusercontent.com/450222/112212406-538d1200-8bf3-11eb-88b2-0b2db01d0b2d.mov
