### ISSUE TITLE
Contentful Tout: the local context menu doesn't show up if we click a linked text to set a url.

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#293]
## Description 
Contentful Tout:  the local context menu doesn't show up if we click a linked text to set a url.

### Steps to reproduce
1. open a page with a contentful tout, e.g. http://0.0.0.0:8005/
2. highlight some text in a body
3. set it as a link
4. click any other text to hide the menu with styles
5. click on the linked text
### Expected result
local context menu with 'link' icon shows, so it can be clicked to open Link form

### Actual result
local context menu doesn't show up

### NOTEs:
the local context menu shows up if the step 4 is skipped. In that case, the menu includes the revert icon and the link icon. 
The cursor is placed in the beginning of the text.
![Screen Shot 2020-04-23 at 3 57 31 PM](https://user-images.githubusercontent.com/3224040/80143764-51ea4280-857b-11ea-8b5b-429dcd55f2dc.png)

### Environment
System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Safari: 11.1
  npmGlobalPackages:
    gatsby-cli: 2.8.29

### Affected Version

reproduced in latest [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/e043bd8b508e1be2fcbd0676116b34550aa39dd6)

**Comment by schristodoulou** [comment]
issue is not reproducible.
