### ISSUE TITLE
Contentful tout: a cursor is placed in the incorrect position in RTE

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#294]
## Description 
Contentful tout: a cursor is placed in the incorrect position in RTE

### Steps to reproduce
1. in Edit environment, open Home page http://0.0.0.0:8005/ (the page with a contentful tout)
2. click Edit
3. in a contentful tout, click on any word in the middle of the tout body  
### Expected result
a cursor locates at the exact place of clicking

### Actual result
a cursor puts in the beginning of the text

### Notes
1. clicking second time moves a cursor to the correct place.
2. a previous position of a cursor is remembered and applied if we click between RTE

**Steps to reproduce:**
1. in Edit mode, open Home page http://0.0.0.0:8005/ 
2. click Edit
3. in a contentful tout, click on any word in the middle of the tout body  
4. click one more time to the same word - > a cursor now shows correctly on that clicked word 
5. click on any word in a Title in the same tout (or a different tout) -> a cursor shows in the beginning of the Title
6. click one more time to the same word to get a cursor in the right position
7. in the body, click any other word different from step3
**Actual Result:**
a cursor is placed on the word from step3.
8. in the title, click any other word different from step5
**Actual Result:**
a cursor is placed on the word from step5.

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.113
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in latest [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/df0075d5c8b856b7be61524e13e90e09c03acf4a)

**Comment by schristodoulou** [comment]
There are too many steps for a user to actually repeat this and it does not make the system appear to be broken. Closing for now.
