### ISSUE TITLE
Notify of Upstream Changes in Edit Environment

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#301]
## User Story

As a content editor
I want to be notified when there are upstream changes
So that I can work with the latest version of the site.

## Acceptance Criteria

AC1.
Whenever a page is loaded in the edit environment
If changes exist on the master branch
Which have not been merged into the current changeset branch
OR if changes exist on the changeset branch
Which have not been pulled to the local environment
A notification to this effect is displayed
Using the notifications API from #300 

AC2.
In addition to page refresh
The following events update the banner:'
- Any git operation (push, pull, status)

**Comment by schristodoulou** [comment]
Note that the "Mark as Read" illustrated in the wireframes is not in scope of this story.
