### ISSUE TITLE
Pull Upstream Changes

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#303]
## User Story

As a content editor
I want to be able to pull upstream changes to the edit environment
So that I can work with the latest version of the site.

## Acceptance Criteria

AC1.
There is a  pull changes button in the main menu (the button [previously removed](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/src/dist/GitProvider.tsx#L122-L139) is restored.
There is text under icon with "Pull"

AC2.
If there are no upstream changes on the changeset branch to pull
The pull changes fly-out panel displays a message to this effect,
and closes without action when submitted.

AC3.
If there are upstream changes, but they require app restart*
The pull changes fly-out panel displays a message
That upstream changes are available but cannot be fetched via the UI
and closes without action when submitted.

AC4.
The pull changes flyout displays a spinner
while gathering the information needed to display the above.

AC5.
Except as noted above
When the pull changes flyout is submitted
The [existing pull changes algorithm](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-backend/src/backend.js#L173-L234) is used to update the local environment
With all changes from the upstream branch

AC6.

When the pull changes flyout is submitted
A modal spinner is displayed while the operation is in progress
And a message is displayed when complete indicating success or failure.

* Changes which require app restart include:
    * Changes to package dependencies (package-lock.json
    * Deleted pages 

## Implementation Notes
- Consider #302  and #304 when designing the API call to get the status required for AC1-3.  In particular, consider having the API return someting like:
```
{
  local: {
   commits: [...],  // commits in local env which are not on master
  },
   upstream: {
    commits: [...], // commits on upstream changeset branch which are not local
    requireRestart: ..., // true if the changes will require app restart.
} 
```

this can later be exended to include data about production.

**Comment by hvanyo** [comment]
Removed -> AC7
The Cloud Up icon that has text "Push"  and moved to another ticket
