### ISSUE TITLE
Filterable item metadata: Local context menu of a hidden item is still visible 

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#308]
## Description
 
Filterable item metadata: Local context menu of a hidden item is still visible 

### Steps to reproduce
1. open /filter-item/
2. click an any item/component
3. assign any default tag to the component. e.g 'foo'
4. filter by that tag (click 'foo') -> the component from step#2 is shown
5. open Group form for that component
6. delete 'foo' tag. click 'v'

### Expected result

Local Context menu of a hidden item is hidden too.

### Actual result

the component is hidden, but its Local Context menu is visible at the top of the page
![Screen Shot 2020-04-29 at 5 57 23 PM](https://user-images.githubusercontent.com/3224040/80742322-320dce00-8ae9-11ea-8f1c-3deecea98ff5.png)

### Environment
System:a
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 80.0.3987.149
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in latest [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/159ccb0351fe6cce932099e08bc6107f458e3707)

**Comment by asiarheyeu** [comment]
Closing as fixed
