### ISSUE TITLE
/rcmenu: the main menu component takes 1/2 width instead of full width. No burger menu is available

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#325]
## Description
/rcmenu: the main menu component takes 1/2 width instead of full width. No burger menu is available
### Steps to reproduce
1. run Edit env
2. open /rcmenu  in a desktop breakpoint (min.1024px)

### Actual Results:
the menu width is in w-1/2.
![Screen Shot 2020-05-12 at 2 01 20 PM](https://user-images.githubusercontent.com/3224040/81729997-e5b47d80-945a-11ea-844d-84ab247babaf.png)
3. resize to a tablet breakpoint (<1024px)

### Actual Results:
The menu disappears. No Burger Menu is shown
![Screen Shot 2020-05-12 at 2 03 27 PM](https://user-images.githubusercontent.com/3224040/81729902-c158a100-945a-11ea-9c23-576a3202b4a1.png)

### Expected result
Main menu should be in  w-full. Also it should transform in Burger menu for tablet/mobile breakpoints

### Environment

System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version

reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/e16e2995dd88e0aca7ec1fbd21586358d327accd)

**Comment by hvanyo** [comment]
@TatsianaMiraniuk 
No burger menu:

- I believe the purpose of this test page is to menu and we don't have expectation that it should work.
- The /burger-menu/  is the test pages where menu & burger-menu is testing.

Half width:

-  I believe it was specifically set to half-width so you didn't have to add as menu test cases to get to the ... feature.

Do you think it would help to put on the top pages a description of purpose of each page.
i.e.  This menu page demonstrates the ability: 
of the Menu component (and link to documentation)
of the Menu components convert to ... when space is limited (1/2 width)
and on pages where we have set SEO, add that, etc..   then map these objectives to your list.
Opinions?

**Comment by TatsianaMiraniuk** [comment]
@hvanyo, thanks!  let's discuss it in standup

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/375
