### ISSUE TITLE
Single accordion: the collapsed item is resized based on Title width (for <1024px - tablet/mobile)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#327]
## Description 
Flow container items are resized based on the underlying component content width (for <1024px - tablet/mobile)

### Steps to reproduce
1.  unzip and copy the data jsons (attached) in /src/data/pages/flow-container
[Archive.zip](https://github.com/johnsonandjohnson/Bodiless-JS/files/4618491/Archive.zip)

2. run Edit env/preview mode. (same in Static)
3. open /flow-container/  (browser is in desktop breakpoint; >=1024) -> the accordions look as expected (1st;2nd;3rd are in full width; 4th;5th are in w-1/2)
![Screen Shot 2020-05-12 at 5 04 44 PM](https://user-images.githubusercontent.com/3224040/81745390-c295c800-9472-11ea-8dcf-05b3eb9a9858.png)

4. change a browser width to a tablet breakpoint (<1024)
### Expected result
the accordions are resized to full width

### Actual result
the accordions are resized based on Title length. 
![Screen Shot 2020-05-12 at 5 04 54 PM](https://user-images.githubusercontent.com/3224040/81745404-cc1f3000-9472-11ea-9af3-40d631cdc12f.png)
If we expand an accordion it takes a full width (correct behaviour)

![Screen Shot 2020-05-12 at 5 05 00 PM](https://user-images.githubusercontent.com/3224040/81745415-ce818a00-9472-11ea-872f-c2ddcddfdac9.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/e16e2995dd88e0aca7ec1fbd21586358d327accd)

**Comment by VancheeZze** [comment]
The issue is not with the accordion component, but rather with `SortableChild` -- component on the Flow Container. On the smaller viewports ( mobile/tablet ) `SortableChild` does not have a default width set making the underlying component take as much space as needed to render its content.
