### ISSUE TITLE
Add remaining Informed components

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#336]
## User Story
As a developer
I want themed versions of all native form input controls
So I can build consistent forms for my components.

## Acceptance Criteria
AC1. All [native informed Input controls](https://joepuzzo.github.io/informed/?path=/story/inputs--intro) are part of [the context menu form UI specification](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-core/src/Types/ContextMenuTypes.tsx#L36)
AC2. Versions of all controls are provided by bodiless-core-ui and themed against the wireframes.
AC3. There is a page on the test site with the examples of the form elements that matches the wireframes (styled only)

## Resource
Wireframes https://jhdfdc.axshare.com/#id=3ct389&p=aries

**Comment by schristodoulou** [comment]
Note: The example page has a "test" icon that is only used on the form elements example page to help illustrate the examples of the form items.
