### ISSUE TITLE
Admin UI: Update Icons and Add Labels to Admin/Context Menu in Editor

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#360]
## User Story

As a Content Editor, I want clear indication of what each icon represents in the Main Menu, so that I can quickly access the functionality I am looking for. 

- The scope of this ticket is to replace the tickets noted in the sub tickets and add Labels to all the admin menu icons that do not have 
- Includes the + icon for the component picker AESQ-1292 
- Includes border surrounding icon and label

### Acceptance Criteria

AC1:

Icons and labels for the Main Menu in the Admin UI match the wireframes https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9 

- Commit Icon = "History" + Icon change
- Cloud Icon = "Save" + label of "Push"
- Revert = Icon has changed, needs label "Revert"
- FlexContainer Icons
-- + = "Add"
-- "Swap"
-- "Delete"

AC2:
Save Icon is available in preview and edit modes

AC3:
The context menu items include labels

- "Add" = plus icon
- "Delete" = trash icon
- "Undo" = undo arrow icon
- "Link" = Link icon
- "Image" = image icon
- "Groups" = groups icon (used in PLP)
- "Edit" = Pencil icon
- "Swap" = swap icon
 

### References

![IconActiveState-correct](https://user-images.githubusercontent.com/59970745/83652481-b04a0e00-a588-11ea-8541-c9dedab950b0.jpg)
![_AESQ-2755__Admin_UI__Update_Icons_and_Add_Labels_to_Admin_Context_Menu_in_Editor_-_Enterprise_Jira](https://user-images.githubusercontent.com/59970745/83652622-d40d5400-a588-11ea-8a27-889c0b3fdf2a.jpg)
![_AESQ-2755__Admin_UI__Update_Icons_and_Add_Labels_to_Admin_Context_Menu_in_Editor_-_Enterprise_Jira](https://user-images.githubusercontent.com/59970745/83652681-e2f40680-a588-11ea-8872-4d13bd764ed6.jpg)

**Comment by asiarheyeu** [comment]
AC4 was removed per agreement with POBA team
