### ISSUE TITLE
Warning "Cannot update a component while rendering another component"

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#380]
## STR
1. Load test-site homepage
2. Put into edit mode
3. Click on CTA link in first Tout
4. Click link button
5. Observe browser console

## ER
No warnings

## AR
```
index.js:2177 Warning: Cannot update a component (`Form`) while rendering a different component (`asField(Text)`). To locate the bad setState() call inside `asField(Text)`, follow the stack trace as described in https://fb.me/setstate-in-render
```

**Comment by hvanyo** [comment]
From a different package @wodenx  

https://github.com/apollographql/react-apollo/pull/3930
As of version 16.13.0, React logs a warning when a function component is updated during another component's render phase (facebook/react#17099).

**Comment by beliayeu** [comment]
per https://github.com/joepuzzo/informed/issues/282 the problem should be fixed by informed update

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/384
