### ISSUE TITLE
Refresh on pull that has upstream changes

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#381]
## User Story

As a content editor
when I pull upstream changes to the edit environment, I want page to refresh
So that I know that site reflects all changes that have been pulled.

### Acceptance Criteria

Refresh page occurs after pull operation that has upstream changes.
AND 
the confirmation from the pull changes informs the user that when they click the check the page will refresh.

**Comment by kbray0009** [comment]
Updates have been successfully pulled.  Page will reflect changes after closing this dialogue.

**Comment by kbray0009** [comment]
New message:  "There are updates available to be pulled. Click check to initiate, page will refresh when done."

**Comment by hvanyo** [comment]
Move the refresh string 
"Operation complete, page will refresh."
and the refresh happens after the  user clicks:  close or check.
