### ISSUE TITLE
Ability to delete page in editor

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#392]
## User Story

- AS A site user/content editor,
- I WANT the ability to delete a page in the editor
- SO THAT I can remove the deprecated page from my site.

### Acceptance Criteria

AC1.
WHEN the user is in the Edit UI and edit mode is active
THEN there is a "Page" icon in the Admin Menu
AND when the User selects the Page Icon
THEN The sub page menu form panel window opens 
AND there is Delete label & TrashCan Icon on the right side.

AC2
When user selects Delete, there is a prompt to ask user if they wish to delete page url,
"Are you sure you want to delete the current page?"

AC3a
If the user selects OK/check, the system will delete the page and associated json files.
tech note: this is pages located in src/data/pages is where deletion will occur.
anything in /static/* assets will not be affected.

AC3b 
During operation in AC3a,  perform usual modal overlay (https://github.com/johnsonandjohnson/Bodiless-JS/issues/410) which is a modal spinner is displayed in the selected panel window,
AND an overlay throughout the screen is displayed while the operation is in progress.
When the operation completes, the spinner is replaced by
-  a status message ("Delete operation was successful. Upon closing this dialog you will be redirected to the deleted page’s parent page.") or 
-  an error message (Warning Icon message: "The page cannot be deleted") in the panel window 
with either message showing the X icon.

AC3c
When the user selects the X icon, reload of the site will happen and the parent page of the deleted page will be displayed.

AC4. In the event of a request timeout, the spinner is replaced by a dismissible status message (Warning Icon message: "The page cannot be deleted, please try again.") in the panel window.

AC5. If the user is on a parent page (had children), when the delete icon is clicked, the user is given a message  an error message (Warning Icon message: "The page cannot be deleted it has child pages. To delete this page, first delete or move all child pages, and retry. ") in the panel window 

### Implementation Notes

Recommend to delete page & json data.
Image media and other items would persist in system as we have no way to tell if the media items are being reused.
Recommend to look at create new page for implementation details.

### References

UX: https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9. (note: we are doing sections in the submenu) 
Just put the delete button to the end of the list in the page menu.

**Comment by hvanyo** [comment]
Andrei's notes:
* do we want to disallow deletion of frontpage?
* when a page is deleted and its parent page does not exist, should user still be redirected to the parent page? or to a closest existing ancestor?
* should we allow deletion of a page containing template data (for instance, /products page defines its own template and template of its child pages in json file)? if it is allowed, then I believe deletion of this kind of pages should not delete the template data

**Comment by mcolares** [comment]
@aeciotr When I try to delete the home page this message appears "Invalid directory "/app/volume/root/examples/test-site/src/data/pages/" to delete".

Maybe I missunderstood but shouldn't give this message instead:
"The page cannot be deleted it has child pages. To delete this page, first delete or move all child pages, and retry. "
or even this one:
"The page cannot be deleted"

@hvanyo Is this the correct behavior?
