### ISSUE TITLE
/link-toggle/ : There is a warning 'Invalid value for prop `unwrap` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.' in Preview Mode if a link value is set for a link toggle component

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#399]
## Description
There is a warning in a console 'Invalid value for prop `unwrap` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior' in Preview Mode if a link value is set for a link toggle component

### Steps to reproduce
1. open Edit env, /link-toggle/ page
2. open a console in a web-browser
3. click Edit button to switch to Edit mode
4. add any text in a link toggle component
5. add a link to the link toggle component
6. click Edit button to switch to Preview mode

### Expected result
no warnings

### Actual result
There is a warning in a console: 'Warning: Invalid value for prop `unwrap` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior'
![Screen Shot 2020-06-25 at 11 16 04 AM](https://user-images.githubusercontent.com/3224040/85955927-0de73580-b950-11ea-9cc0-546080f9b73e.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

**Comment by VancheeZze** [comment]
Closing as not reproduced.
