### ISSUE TITLE
/flow-container/: there is a warning: 'React has detected a change in the order of Hooks called by EditFlowContainer. This will lead to bugs and errors if not fixed.' when adding a component

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#401]
## Description
There is a warning in a console: 'Warning: React has detected a change in the order of Hooks called by EditFlowContainer. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks' when adding a component from Component Picker

### Steps to reproduce
1. open Edit env, /flow-container/ page
2. open a console in a web-browser
3. click Edit button to switch to Edit mode
4. click a flow container area
5. click + in Editor Menu
6. in Component Picker, select any component 

### Expected result
no warnings

### Actual result
there is a warning in a console: 
Warning: React has detected a change in the order of Hooks called by EditFlowContainer. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks
![Screen Shot 2020-06-28 at 4 04 49 PM](https://user-images.githubusercontent.com/3224040/85957165-24de5580-b959-11ea-998d-ebb016289f72.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

**Comment by VancheeZze** [comment]
Closing as not reproduced
