### ISSUE TITLE
/gallery-final/: There are 2 warnings in a console:  'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.' when loading the page

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#403]
## Description
There are 2 warnings in a console: 
'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.' when loading /gallery-final/ page (Edit and Preview modes)

### Steps to reproduce
1. open Edit env, /gallery-final/ page
2. open a console in a web-browser

### Expected result
no warnings

### Actual result
there are two warnings in a console: 
'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
In Preview and Edit modes
![Screen Shot 2020-06-28 at 4 52 44 PM](https://user-images.githubusercontent.com/3224040/85957966-d6808500-b95f-11ea-98d1-82273cc60c4e.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

**Comment by hvanyo** [comment]
Similar bug -> https://github.com/johnsonandjohnson/Bodiless-JS/issues/354
