### ISSUE TITLE
Image component: there is no padding in mobile view (=<767px)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#405]
## Description
Image component: there is no padding in mobile view (=<767px)

### Steps to reproduce
1. open Edit env, /flow-container/ page
2. click Edit button to switch to Edit mode
3. add any two image components and upload the images
4. switch to Preview Mode
5. set the browser width to =<767px

### Expected result
there is a space between the images

### Actual result
there is no space between the images
![Screen Shot 2020-06-28 at 5 42 06 PM](https://user-images.githubusercontent.com/3224040/85958846-b99b8000-b966-11ea-9e11-cee7b5d790a7.png)

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

**Comment by schristodoulou** [comment]
We have not defined UX patterns for Mobile in Edit Mode.
