### ISSUE TITLE
There is a warning in a console 'Can't perform a React state update on an unmounted component...' (sporadically)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#431]
## Description 

There is a warning in a console 'Can't perform a React state update on an unmounted component...' (sporadically)

### Steps to reproduce
1. open Edit env, home page
2. open a console

### Expected result

no warning in a console

### Actual result
the warning 'Can't perform a React state update on an unmounted component..' appears sometimes
![Screen Shot 2020-07-10 at 5 27 23 PM](https://user-images.githubusercontent.com/3224040/87204653-5baa5900-c2d3-11ea-8cf3-f37a5a776792.png)

### Environment
platform.sh - deployed by Bodiless CLI

### Affected Version
reproduced in Master

**Comment by asiarheyeu** [comment]
Fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/854
Closing as completed
