### ISSUE TITLE
Allow adding.removing classes conditionally via fclasses.

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#432]
## User Story
As a site builder
I want to be able to use the design API to toggle styling based on component state
So that I can implement dynamic designs.

## Background

The current bodiless way to do this is to use a flowToggle and put a different component in place depending on state, eg:
```
const Component = designable(..)({ Title, Body }) => {
  const [on, setOn] = useState(false);
  return (
    <Wrapper on={on} >
      <Body />
    </Wrapper>
  );
};
const useToggle = props => props.on;

const asColoredWrapper = withDesign(
  Wrapper: flow(
    ifToggledOn(useToggle){removeClasses(blue), addClasses(red))),
    ifToggledOff(useToggle)(removeClasses('red'), addClasses('blue')),
  ),
);
```
The problem here is that when this toggle is triggered, the entire component tree under the Wrapper will be destroyed and re-rendered bc the Wrapper component itself is being swapped.  The problem is illustrated in [this code sandbox](https://codesandbox.io/s/dreamy-tereshkova-zc50d).

As an alternative, we want an API which allows
```
const asColoredWrapper = withDesign(
  Wrapper: flow(
    addClassesIf(useToggle)('red'),
    removeClassesIf(useToggle)('blue'),
    addClasesIfNot(useToggle)('blue'),
     removeClassesIfNot(useToggle)('red')
  ),
);
```
In wihch case the actual component rendered will remain the same (I think), an donly the props will be toggled.

In scope of this we should also add `addPropsIf`, `addPropsIfNot`, `removePropsIf` and `removePropsIfNot` which can be used where something other than classes need to be modified.

## Acceptance Criteria

- The fclasses api has a toggle styling based on component state.
- The documentation is updated accordingly.
- Test cases exist or updated for changes.

**Comment by hvanyo** [comment]
Address in scope of https://github.com/johnsonandjohnson/Bodiless-JS/issues/390
