### ISSUE TITLE
In non-active menu items should have greyed out label as well

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#435]
## Description

When menu icon is not available to use, both the icon and label should be greyed out.

### Steps to reproduce

1. Be in Edit environment where you don't have ability to push/save.

### Expected result
both the icon and label should be greyed out.
![2020-07-13_14-22-10](https://user-images.githubusercontent.com/58534559/87344546-47a16a00-c514-11ea-8a55-679c8c50a98b.jpg)

### Actual result
Only the icon is greyed out.
![2020-07-13_14-20-58](https://user-images.githubusercontent.com/58534559/87344458-17f26200-c514-11ea-8bd5-6a81f5f516f2.jpg)

### Environment

https://edit.master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/  

### Affected Version

- v0.0.51

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/516
