### ISSUE TITLE
Implement Interface for Managing Meta Data

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#450]
## Description
As a Content Editor, I want the ability to manage meta data via the interface, so that I do not have to bring in a developer to manage the content. 

https://jhdfdc.axshare.com/#g=1&p=generic_ui

*Form Title:* 

SEO Data Management  

**Form Description Text:**

Enter the page level data used for SEO. This is metadata needed for SEO that will go in the head of the script.  

**Form fields:**
|*Title*|*Field*|*Placeholder text to appear in field*|
|Title|Text Field|rec 30-65 char|
|Description|Long Text Field|rec <160 char|
|Page Type|Text Field| |

Notes:
- No validation 
- No scrolling of the form because it's only 3 pieces 
- Keep in mind that this form may be combined with another form such as GTM meta data at a later time 
- Long text field should be 3 lines high
  

 
## Acceptance Criteria
AC1: The Content Edit UI Main Menu includes an "SEO" Icon and label 

AC2: Clicking on the "SEO" Icon opens a form panel (form.png) that has a:
- Form Title: "SEO Data Management"
- Form Description: "Enter the page level data used for SEO. This is metadata needed for SEO that will go in the page header."
- Form Fields
  - Title, Description and Page Type
  - Text box fields
- The checkmark and X work as expected same as the other panel windows work.

AC3: The data is used and stored from the meta data, the metadata storage structure stays the same

AC4: There are standard set of metatags for title, description and page type which can be added to the page, along with the associated form with little to no code duplication 

AC5: Default placeholders match the text in the description and the values of the fields are empty values. 

## Attachments
<img title="ZoomAnnotationContentWnd.png" src="https://user-images.githubusercontent.com/59970745/87707795-b29aad00-c76f-11ea-91e2-f389e90feaa7.png" width="200" />

**Comment by dewen** [comment]
Question regarding <title> tag rendering: If the value is empty string, should the title tag get rendered?

@schristodoulou @hvanyo ^^

**Comment by hvanyo** [comment]
@dewen  prefer not but that is current behavior.  We gapped in the last meta tag implementation.  If title or other meta are empty and then don't render it, that is preferred behavior.  So if you address it now we close the gap and if you don't we leave gap open.

**Comment by dewen** [comment]
I added title empty check and hide <title> tag if content is empty. But Helmet might have logic to render a default one if no user title overrides.
