### ISSUE TITLE
Multilingual Considerations

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#473]
Starting this as a catch all for things we will need to change if we decide to support multilingual sites (rather than simply treating each language as a separate site).
- Managing <html> head element.  Currently this is set at site level and defines a single language.  We'd need a mechanism for setting the value per language and selecting the right one.
- GDPR UUID
- BV language

**Comment by hvanyo** [comment]
TO do -- > Discovery with committee how they want to handle/work with multilingual sites.
@e2thex  @schristodoulou
