### ISSUE TITLE
/carousel/ Warnings "Failed prop type: Invalid prop `autoplayInterval` of type `string` supplied to `Carousel/Wrapper`, expected `number`" are displayed in the console

### ISSUE THREAD

**Issue by NTenyush** [johnsonandjohnson/Bodiless-JS#508]
## Description

On the Carousel page following warnings are presented:
1. index.js:2177 Warning: Failed prop type: Invalid prop `autoplayInterval` of type `string` supplied to `Wrapper`, expected `number`;
2. index.js:2177 Warning: Failed prop type: Invalid prop `autoplayInterval` of type `string` supplied to `Carousel`, expected `number`.

### Steps to reproduce

1. Open Edit env, page /carousel/;
2. Open a console in a web-browser;

### Expected result

No warnings

### Actual result

There are following warnings:
1. index.js:2177 Warning: Failed prop type: Invalid prop `autoplayInterval` of type `string` supplied to `Wrapper`, expected `number`;
2. index.js:2177 Warning: Failed prop type: Invalid prop `autoplayInterval` of type `string` supplied to `Carousel`, expected `number`.
<img width="555" alt="warnings carousel" src="https://user-images.githubusercontent.com/69196219/90475051-5f7d9680-e12f-11ea-824a-64fb337fd8ff.PNG">

### Environment

 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.125
    Edge: Spartan (44.18362.267.0)
  npmGlobalPackages:
    gatsby-cli: 2.12.87

### Affected Version

reproduced in Master

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/975
