### ISSUE TITLE
/burger-menu/ Menu and sub-menu titles can't be easily filled in

### ISSUE THREAD

**Issue by NTenyush** [johnsonandjohnson/Bodiless-JS#509]
## Description

Menu/sub-menu items can't be easily typed on the /burger-menu page

### Steps to reproduce

1. Open Edit env, Burger Menu page (/burger-menu);
2. Click Edit button to switch to the Edit mode;
3. Type any text in the first level Menu Item;
4. Observe the result;
5. Add sub-menu item;
6. Type any text for the sub-menu.

### Expected result

Menu titles are easily filled in.

### Actual result

In order to fill in anything one needs to click on letter several times.

### Environment

 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.125
    Edge: Spartan (44.18362.267.0)
  npmGlobalPackages:
    gatsby-cli: 2.12.87

### Affected Version

reproduced in Master

**Comment by TatsianaMiraniuk** [comment]
not reproduced anymore
