### ISSUE TITLE
Pointer of SEO Data Management form is dislocated

### ISSUE THREAD

**Issue by NTenyush** [johnsonandjohnson/Bodiless-JS#514]
## Description

Pointer of the SEO Data Management form isn't displayed near the SEO icon

### Steps to reproduce

1. Open Edit env on the screen with height <=756px;
2. Click on Edit icon;
3. Click on SEO icon;
4. Compare with designs https://github.com/johnsonandjohnson/Bodiless-JS/issues/450;

### Expected result

Pointer is displayed near the SEO icon

### Actual result

Pointer is displayed near the allure icon
<img width="313" alt="SEO form 756px" src="https://user-images.githubusercontent.com/69196219/90601265-9b346100-e200-11ea-9d91-e82f76ea7bff.png">

### Environment

System:
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Binaries:
Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: 84.0.4147.125
Edge: Spartan (44.18362.267.0)
npmGlobalPackages:
gatsby-cli: 2.12.87

### Affected Version

https://github.com/johnsonandjohnson/Bodiless-JS/pull/485

**Comment by asiarheyeu** [comment]
Bugscrub notes: Closed as won't fix as an acceptable degradation of UI
