### ISSUE TITLE
Component Picker: checking 'All' checkbox doesn't reset other checked categories. Checking any filter option doesn't reset/uncheck 'All' checkbox

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#557]
## Description

Component Picker: checking 'All' checkbox doesn't reset other checked filter categories. Checking any filter options doesn't reset/uncheck 'All' checkbox

### Steps to reproduce - scenario A
1. open Edit env, any page with a flow container, e.g. /flow-container/ 
2. switch to Edit mode
3. click inside an empty flow-container
4. click Add+ in Editor Menu to open Component Picker
5. check any option in Type, e.g. 'Image'
6. check 'All'
### Expected result
'Image' is reset/unchecked. 'All' only is checked.
### Actual result
'Image' is still checked.

7. uncheck 'Image'
### Actual result:
'All' only is checked. But only 'Image' components are displayed.
![ImageOnly](https://user-images.githubusercontent.com/3224040/93378240-287fcb00-f82a-11ea-8dbd-2da173584468.png)

### Steps to reproduce - scenario B
1. open Edit env, any page with a flow container, e.g. /flow-container/ 
2. switch to Edit mode
3. click inside an empty flow-container
4. click Add+ in Editor Menu to open Component Picker
5. check 'All'
6. check any option in Type, e.g. 'Image'
### Expected result
'All' is reset/unchecked. 'Image' only is checked.
### Actual result
'All' is still checked.

7. uncheck 'All'
### Actual result:
'Image' only is checked. But all components are displayed.
![AllUnchecked](https://user-images.githubusercontent.com/3224040/93377766-75af6d00-f829-11ea-8785-079b565bcfeb.png)

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/8ae1edb3457a91b1013125209d7dd22e2f0ea7fd)

**Comment by asiarheyeu** [comment]
Closed as a won't fix since checkbox "All" was deleted according to the requirements
