### ISSUE TITLE
Add Follow Link in Context Menu

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#585]
## Description
As a Content Editor, when I am working in Edit Mode, I want to quickly navigate through the site without having to click the Edit button. 

https://jhdfdc.axshare.com/#g=1&p=menus&id=rz3u0f 

 
## Acceptance Criteria
AC1: When in Edit Mode, The Context Menu for linkable objects includes a "Go" icon and label as to the left of the link icon, examples:
- Menu and Submenu items
- Text links
- CTAs
- linkable Images

AC2: Clicking on the "Go" link navigates to the item's URL and the user stays in edit mode

AC3. If there is a link toggle and it is toggled as off and/or there is no href value then the "Go" button is disabled.

**Comment by asiarheyeu** [comment]
Closing as completed
