### ISSUE TITLE
Keep submenu displayed when item's context is active

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#587]
## user Story
As a content editor
I want submenus (list, tout and column items) to remain visible while i edit them
So I don't become excessively frustrated.

* NOTE this is mainly a testing story, the work has already been completed in a different story.

## Acceptance Criteria

AC1.
When a submenu item is Active
The submenu to which it belongs remains visible
Even if the mouse hovers away form the submenu.

**Comment by asiarheyeu** [comment]
Closing as competed
