### ISSUE TITLE
Example site: touts can't be resized to less than 50% width on tablet screen

### ISSUE THREAD

**Issue by konst8** [johnsonandjohnson/Bodiless-JS#591]
### Steps to reproduce

1. Setup the example site and narrow the browser screen down to around 980px (tablet width).
2. Switch to edit mode and try to resize touts on the home page in order to get 3 touts in a row.

### Actual result

The minimum allowed width of the resizable tout is 50%.

![image](https://user-images.githubusercontent.com/6871275/95325228-8c396900-08a9-11eb-987c-a1a70ab0f865.png)

### Expected result

Tout width can be set to 33% or less on the table screen.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 14.0

### Affected Version

0.0.56

**Comment by hvanyo** [comment]
Will potentially be fixed https://github.com/johnsonandjohnson/Bodiless-JS/issues/591
