### ISSUE TITLE
Fix Resizing of Component in flow Container at different break points

### ISSUE THREAD

**Issue by e2thex** [johnsonandjohnson/Bodiless-JS#598]
## Description
Issue 1:
Main issue is that w-full isn't added by default.
Leading to bugs such as https://github.com/johnsonandjohnson/Bodiless-JS/issues/327
Issue 2:
We don't have the all the breakpoints at tablet size for resizing.
Issue 3:
When resizing, width is removed when resizing ends
Issue 4:
Fix default width to use classes instead of %'s.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

- If the issue was encountered on a site, please attach your `package.json`
- If the issue was encountered in the Bodiless-JS repo, please link to a
  commit or branch on which the issue occurs.

**Comment by hvanyo** [comment]
Potentially fix -> https://github.com/johnsonandjohnson/Bodiless-JS/issues/327
