### ISSUE TITLE
[DOC] Images Not Appearing in BodilessJS Docs

### ISSUE THREAD

**Issue by malachye** [johnsonandjohnson/Bodiless-JS#611]
## Description

Images not appearing in BodilessJS documentation

### Steps to reproduce

1. Add images to assets folder of bodiless package (e.g https://github.com/johnsonandjohnson/Bodiless-JS/tree/master/packages/bodiless-layouts/assets)
2. Add image to README for documentation via markdown (e.g. https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-layouts/README.md)
3. Run BodilessJS documentation.

### Expected result

The Images added to assets folder of individual packages should appear rendered in docisfy in BodilessJS docs (e.g. https://github.com/johnsonandjohnson/Bodiless-JS/tree/master/packages/bodiless-layouts/assets)

### Actual result

Images do not render for packages (e.g . https://johnsonandjohnson.github.io/Bodiless-JS/#/Components/FlowContainer)

### Affected Version

Master

**Comment by asiarheyeu** [comment]
Closed as completed
