### ISSUE TITLE
Highlighting Link in Tout replaced it with actual href link ON Starter Site

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#616]
Repeat of : https://github.com/johnsonandjohnson/Bodiless-JS/issues/161
Fix: https://github.com/johnsonandjohnson/Bodiless-JS/pull/306 on test-site
and needs to be addressed on starter site as its replicating through site builds

**NOTE**:  DURING discussion, if we continue on this pattern we ahve to add this workaround/fix at everypoint a link is used.  It was determined to move this fix to the link package level so it takes effect for all link cases.

## Description

If you try highlight a linked tout cta, it replaces it with the actual href link

### Steps to reproduce

1. place a tout and link the cta and name the cta link (or use existing tout that has linked CTA)
2. highlight the CTA link (to copy it elsewhere)

### Expected result

Highlights as expected

### Actual result

Highlighting injects the href value into the text cta title.
https://www.screencast.com/t/qbmrsFj4f8Su

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by asiarheyeu** [comment]
closed as completed
