### ISSUE TITLE
Add type checking to sites

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#617]
## User Story
As a developer
I want proper type checking when working on sites
So that I can work more efficiently

## Acceptance Criteria
AC1. The starter kit, test site and demo-site are configured to perform type checking and linting during build, both in the monorepo and as standalone sites. 
AC2.  All type and linting errors are remediated.
AC3. By default when a site is created from the starter kit or the test site, the repository is configured to perform linting on push. 

## Implementation Notes
we probably want to revisit how we type HOC's, and ensure that all our tokens and other HOC's adhere to the same signature, which should be something like, includes YAML files
```
type ComponentOrTag<P> = ComponentType<P>|keyof JSX.InstrinsicElements;
type HOC<P = any, Q= {}> = (Component: ComponentOrTag<P>) => ComponentOrTag<P & Q>
```

**Comment by hvanyo** [comment]
Fixed issue
