### ISSUE TITLE
Implement reusable modal overlay and use in create page & revert

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#63]
## User Story

- AS A content editor
- I WANT to know that a long running operation is in progress, and when it completes
- SO THAT i don't get confused 

### Background/Description

Current lengthy operations include create page, pull/push changes, revert, etc.  These now terminate with an alert, and no progress indicator.  This needs to be improved.

### Acceptance Criteria

AC1. There is a bodiless core API to display a modal spinner AND an overlay throughout the screen while a time consuming operation is in progress. 

AC2: When the operation completes, the spinner may replaced by a dismissible status message ("Done") or a error message ("Error" _Text grey 100_) in the panel window with the X icon.

AC3. When the operation completes, the spinner may be dismissed without a status message.

AC4. If the operation does not complete within a timeout (set when invoking the library), it is replaced with an error message as in AC2.

AC5. The actual components used to render the spinner are injectable via a ui prop, and the defaults are exported from the `bodiless-core-ui` package.

AC6. The above spinner is implemented for the create page operation so that:

AC6a. When I confirm the create page operation the spinner is displayed
AC6b. When the create page operation completes successfully, I am immediately redirected to the new page.
AC6c. When the create page operation times out (10s) or errors (eg page already exists), the spinner is replaced by an error message as in AC3.

AC7a. When I confirm the revert operation the spinner is displayed until the operation success dialogue is shown. 
AC7b. When the revert operation completes successfully, the page is reloaded
AC7c. When the revert page operation times out (10s) or errors (eg page already exists), the spinner is replaced by an error message as in AC3.

### References

Design: https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9:  Click "File" then "Pull" then confirm by clicking the Check icon.

**Comment by hvanyo** [comment]
Before starting, confirm if we need to do this on revert after all the changes being done on revert/update.

Possible acs to add:
AC7a. When I confirm the revert operation the spinner is displayed
AC7b. When the revert operation completes successfully, the page is reloaded
AC7c. When the revert page operation times out (10s) or errors (eg page already exists), the spinner is replaced by an error message as in AC3.
