### ISSUE TITLE
Create json files for scraped images

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#641]
## User Story
As a site migrator
I want data for the images on a page automatically written to the page directory
So I can more quickly locate and select images

## Acceptance Criteria

AC1. When the migration tool downloads an image for a page, it places a json file containing image src and alt text (in the schema defined by the bodiless image component) into the /src/data/pages/... directory for the corresponding page.
- The src is the relative url of the downloaded image.
- The alt text is the alt text from the original site.

AC2. The filename of the json file is created by prefixing the name (without extension) of the original image with a string which can be specified as a configuration option, eg:
```
imageDataPrefix: '___assets$`
```

AC3. The above behavior can be enabled/disabled by a configuration option.

**Comment by hvanyo** [comment]
I think its worthwhile here to put in option if it should grab the optimized or non-optimized image.
- Especially for adaptive images.
- Some other drupal styles may be doing cropping ..  

Non-optimized images:  as images are retrieved, use the original image path and NOT drupal image /styles/ or /adaptive_image/ styles.

**use case of site using adaptive images:** 
https://www.johnsonsbaby.com/baby-products/johnsons-baby-bath-gift-set

- /files/styles/jjbos_adaptive_images_generic-desktop/public/product-images/bath_discovery_baby_gift_set_1.jpg
- but original image by adapting the url path (remove /files/styles/jjbos_adaptive_images_generic-desktop/public) to get 
- /files/product-images/bath_discovery_baby_gift_set_1.jpg 

**use case of site using just drupal styles images:** 
https://www.listerine.co.uk/products/fresh-breath/listerine-total-care

- https://www.listerine.co.uk/sites/listerine_uk/files/styles/product_image/public/product-images/total_care.png
- but original image by adapting the url path (remove /styles/) to get 
- https://www.listerine.co.uk/sites/listerine_uk/files/product-images/total_care.png


Current styles that crop
![2020-10-28_09-41-09](https://user-images.githubusercontent.com/58534559/97452561-7cd29c00-18fa-11eb-878b-61cd267b723a.png)
