### ISSUE TITLE
Migration tool options for site skeleton

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#643]
## User Story
As a site builder
I want to configure the migration tool not to create index files for pages
So I can use it more efficiently to create a site skeleton

## Acceptance criteria
AC1. It is possible to configure the name used by the migration tool to write the main index.jsx file for a page
AC2. It is possible to configure the migration tool not to create any jsx files for a page

**Comment by hvanyo** [comment]
AC3 - can we use the page type to map these...

see JIRA ticket for idea.
