### ISSUE TITLE
Flow container writes data unnecessarily

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#656]
## STR
1. Create a contentful flow container
2. Visit the page with that flow container
3. Click on the first item in the flow container

(Note - A contentful flow container is now available on test site at /flow-container

## ER
No json file is written

## AR
A json file is written with all current items.

## Impact
Updates to the default content will not propagate to the flow container bc the content has now been overridden.

**Comment by hvanyo** [comment]
@wodenx 
In testing this .json file are created for any RTE fields when I click on them :Title, body, CTA link
https://www.screencast.com/t/OR4gpi8zu

**Comment by wodenx** [comment]
@hvanyo I believe that is an unrelated issue - it happens on rich text editors outside the flow container, eg at /richtext.  Perhaps we should open a separate ticket for it.

**Comment by hvanyo** [comment]
Created https://github.com/johnsonandjohnson/Bodiless-JS/issues/661
