### ISSUE TITLE
Deleting json file for any component does not reset content until manual page reload

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#66]
Removing content files do not trigger a rebuild - and, when rebuilt, may not actually update data.

*STR1.*

1. Visit edit environment
 2. Modify a component ie. tout title
 3; Note json file created in directory.
 4; Delete json file

*Expected Result*
 * Component data will automatically revert to the default value without manually reloading the page

*Actual Result*
 * Component data remains in altered state from #2 above until manual page reload

Related Issue:
## Related Issues
#65 
https://github.com/johnsonandjohnson/Bodiless-JS/issues/146

**Comment by wodenx** [comment]
Deleting the file does in fact trigger a data refresh - the problem is that when we process the data into the store, we don't remove nodes from the store that don't exist in the data.  Change needs to be made in `updateData` method of `GatsbyMobxStore`

**Comment by beliayeu** [comment]
@wodenx, I believe the second problem (page deletion case) is a gatsby level issue. please see https://github.com/gatsbyjs/gatsby/issues/17402

**Comment by schristodoulou** [comment]
Removed the second issue and created https://github.com/johnsonandjohnson/Bodiless-JS/issues/146.
