### ISSUE TITLE
Component Library: Add "Clear" Functionality for Filters

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#668]
## Description
 

As a Content Editor, I want to clear out my selected filters so that I can quickly start my selection process from the beginning  

 
## Acceptance Criteria
AC1.

There is no "All" label with checkbox

AC2.

There is a "Clear" link in the same place where the "All" was (see mockups)

AC3.

When there are no filters selected then the "Clear" link is disabled 

AC4.

When the are filters selected then the "Clear" link is enabled 

  AND

When the link is clicked it clears out the filters selected in the component picker

  AND

ALL components render as expected

AC5.

There is a style on the "Clear" link for each enablement that follows the patterns of the admin tool bar

**Comment by wodenx** [comment]
Gap - I believe we want the clear link to be enabled when there is text in the search field, but this is not mentioned in the AC's - I think this can be fixed in scope of #667.
