### ISSUE TITLE
Dup content on test site footer

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#679]
### Steps to reproduce

1. Open master build:
https://master-7rqtwti-jvaff4bu65vgm.us-2.platformsh.site/

2. Check footer content, 
"This site is published by Johnson & Johnson Consumer Inc., Last Updated:  Last Updated: 11/11/2020"
where "Last Updated" repeated.

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

- If the issue was encountered on a site, please attach your `package.json`
- If the issue was encountered in the Bodiless-JS repo, please link to a
  commit or branch on which the issue occurs.

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/688
