### ISSUE TITLE
Add follow link button

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#68]
## User Story

- AS A Content Editor
- I WANT to be able to navigate the site while in edit mode
- SO THAT I don't waste time switching back and forth to non-edit mode

### Acceptance Criteria

AC1.
When I click on a link in edit mode
There is a follow-link button on the context menu

AC2.
When I click the follow link button
The browser acts as though I had clicked the actual link
(eg loads the target page)

**Comment by hvanyo** [comment]
Suggest default be in new tab

**Comment by hvanyo** [comment]
dup of https://github.com/johnsonandjohnson/Bodiless-JS/issues/585
