### ISSUE TITLE
Component Switcher

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#69]
## User Story
As a content editor
I want to be able to replace one component with another
So I have control over the content on my page.

## Acceptance Criteria

AC1.
There exists a "component switcher" component
Which adds a button to the menu
Allowing you to select what component it should render
Using the existing component selector.

AC2.
If content data exists for the first component
The new component gets the same data.

AC3.
If the new component has a different data schema
It will act as though it had no initial data
And the data for the original component will be ignored.

## Implementation Note

Implement by creating a special case for flexbox.

**Comment by hvanyo** [comment]
Switcher & Plus + can both be activated.

STR:

1. Visit a page with flexbox
2. Click Switcher
3. Click + (Add)
4. Choose component

ER
Maybe you can't choose both Switcher & +
AR
Component is added to page, Component PIcker stays up, Choosing another component closes window

https://www.screencast.com/t/wcKsVPIytfC

**Comment by hvanyo** [comment]
Observation (no action needed or maybe document somewhere)
If we keep our components named with similar patterns,
Tout has "Title" "Body" and Accordion has "TItle" "Body" -- these "not like" components switch back & forth just fine.

I assume something that had an Image like a Tout -- would switch back & forth as nicely.. I don't have that example to try out.

Another thought if the "Body" could switch out with Basic/Simple/Full RTE that might be kind of cool. But that is beyond scope of this ticket. but if it was easy.. :)

> Did you try this? I think it should "just work" as long as all editors use subsets of the same components.

I did try and it didn't work. :( I wanted to see behaviors when I replaced with non-similar components, so started replacing everything with anything.

I think going forward we should try keep the naming of items in components similar with same-items as the component switcher is useful in preserving the data in some form saving content editor time.

**Comment by hvanyo** [comment]
@schristodoulou  
Were we going to put the Names under the all the icons in editor admin bar?   or only some.
My feedback here is not sure if I would understand the repeat button is used for switching my component.  "Switch" under might give me more of a clue.  
https://www.screencast.com/t/Rfa4YqubtEk
