### ISSUE TITLE
Menu flicker on static site

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#698]
STR
1 Build static site
2. Visit any page with desktop viewport (most evident on /megamenu)

ER
Main menus appear when page loads

AR
Page renders with no menus and they pop up a moment later.

Notes - probably due to rendering mobile view during build - mobile menu is then unmounted and desktop mounted during rehydration.  Probably should be fixed by rendering both and hiding with media queries.

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/697
