### ISSUE TITLE
Search field in the header is not adapted for mobile view breakpoints (<535px)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#699]
### Steps to reproduce
1. in a browser, set a width 534px or less
2. open Static env, Home page

### Expected result
Search field is adapted for mobile view breakpoints

### Actual result
Search field broken, Site Logo is squeezed
![Screenshot_20201118-101716_Chrome](https://user-images.githubusercontent.com/3224040/99549389-96aa5080-2987-11eb-910d-bc849c0fe2d7.jpg)

### Affected Version
reproduced in Master

**Comment by schristodoulou** [comment]
Converting this issue into a story, there will be another ticket.
