### ISSUE TITLE
New Site Initialization on Platform.sh fails

### ISSUE THREAD

**Issue by virtuz** [johnsonandjohnson/Bodiless-JS#71]
## Description
I'm trying to follow documentation of new site creation and platform.sh initialization, but run into npm error.

Refs:
https://johnsonandjohnson.github.io/Bodiless-JS/#/About/GettingStarted?id=creating-a-new-site
https://johnsonandjohnson.github.io/Bodiless-JS/#/Development/OtherResources/Platform.sh?id=step-2-initialize-your-project-configuration-files

### Steps to reproduce

New site creation:
git clone https://github.com/johnsonandjohnson/bodiless-js.git
cd bodiless-js
npm ci
npm run new
cd ~/gatsby-starter-bodiless
P.sh initialization:
npm i --save-dev @bodiless/psh
Add the following to your package.json scripts:
"init-psh": "bodiless-psh-init"
Install or update the configuration files:
npm run init-psh

### Expected result

the following command run successfully:
npm run init-psh 

### Actual result

npm run init-psh

> @bodiless/gatsby-starter-bodiless@0.0.37 init-psh /home/abullo/gatsby-starter-bodiless
> bodiless-psh-init

Initializing platform.sh configuration...
Generating docs/package-lock.json...
exec error: Error: Command failed: npm --prefix ./docs install --package-lock-only
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @bodiless/gatsby-theme-bodiless@^0.0.35.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'docs'
npm ERR! notarget

**Comment by wodenx** [comment]
This is a test comment
