### ISSUE TITLE
Home Burger Menu is getting assign an object for overview

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#721]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Visit the home page of bodiless.

### Expected result

No object's to overview.

### Actual result

```
<li data-bl-design-key="List:Item" overview="[object Object]" data-bl-activator="true" class="pl-3">...</li>
````

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

https://github.com/johnsonandjohnson/Bodiless-JS/commit/f6aca9be2323907d86ec8801f763cb0232284a2b

**Comment by hvanyo** [comment]
![2020-11-25_15-15-58](https://user-images.githubusercontent.com/58534559/100282415-296f6000-2f31-11eb-9f96-98b3469a3640.jpg)

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/841
