### ISSUE TITLE
Warning:  the request of a dependency is an expression

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#727]
## Description

Describe the issue that you're seeing.

### Steps to reproduce
Start test site: npm run start  
### Expected result
No warning

### Actual result

Warning:
"@bodiless/test-site: warn Critical dependency: the request of a dependency is an expression"

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

0.0.61

**Comment by TatsianaMiraniuk** [comment]
not reproduced anymore
