### ISSUE TITLE
Images use FluidWithWebpGatsbyImage lose their alt & styling class

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#733]
## Description

Images that use GatsbyImage lose their alt & styling applied via design

### Steps to reproduce

Activate images  via gatsbyimage

````
const FluidWithWebpGatsbyImage = asFluidWithWebpGatsbyImage(Img);
const asSquareImage = asEditableImage;
const SquareImage = asSquareImage(DEFAULT_IMAGE_NODE_KEY)(FluidWithWebpGatsbyImage);
````
Add an image and set 'alt' text

elsewhere set design for that image
````
withDesign ({
    Image: asRoundedTop,
})
````

### Expected result

 The alt is preserved the image still maintains it classes 

### Actual result

The alt is not transferred & styling is put on higher div and doesn't take effect.

### Environment

Tested on master /images page that uses Fluid With Webp

### Affected Version

Bodiless 0.0.61

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/734
