### ISSUE TITLE
Mega/Simple Menu: 'Superscript' Context Menu isn't hidden when any Admin Menu form gets open.

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#737]
## Description
Mega/Simple Menu: 'Superscript' Context Menu isn't hidden when any Admin Menu form gets open.

### Steps to reproduce
1. open Edit env, any page
2. switch to Edit mode
3. in Main Menu, add an item
4. type any text in the item
5. highlight any text to get Local Context Menu
6. select 'superscript' option
7. click File (or any icon in Admin Menu that has a form)

### Expected result

Context Menu closes

### Actual result

Context Menu stays visible
![Screen Shot 2020-12-03 at 3 50 24 PM](https://user-images.githubusercontent.com/3224040/101086734-4a623180-357f-11eb-84c4-d96b5f67d294.png)

NOTE: 
it was pulled out from #577

### Affected Version
reproduced in Master

**Comment by irkhodzka** [comment]
The issue is not relevant, as menu items currently have no superscript styling
