### ISSUE TITLE
[DOC] Update Site Build Basics Section to Reflect Bodiless Concepts

### ISSUE THREAD

**Issue by malachye** [johnsonandjohnson/Bodiless-JS#758]
The purpose of this page is to provide a tutorial for working with a Gallery page. 
 * Update the Title to refer to the content that is more about Bodiless Concepts ie. "Intro into Bodiless Concepts"
 * Update the Intro message. This is a tutorial to introduce basic Bodiless concepts to a developer and will produce a gallery page in a new page
 * Need screenshots and links to the code example
 * Headings are all referring back to the Gallery page, recommend Updating titles as needed to make the flow of the page better reflect that this is a tutorial for the Gallery page and not for generically building out a site. 
 * The second part of the tutorial is the "Design Element Basics" which should also include "Concepts" into the title
 * Also review the "Design Element Basics" Intro and clean up to better fit the tutorial and make sure it flows from the previous section.

**Comment by asiarheyeu** [comment]
Closing as completed
