### ISSUE TITLE
Allow ability to add buttons to be added to toolbar

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#794]
## User Story
As a site builder
I want my component to add buttons to the admin toolbar
via an api interface so that they visible in the toolbar and not just in context.

## Acceptance Criteria
AC1. It is possible to configure a component to add buttons to the (global admin) toolbar.
AC2: In the tool bar, when selected the Page button opens a sub panel for "Page" with the "New Page" icon and label
AC3. When the user selects the "New Page" button the "Add Blank Page" form appears with same behavior as it does now.
AC4. There is a test case on the Chameleon page on the Test site, in which a chameleon adds a button to the tool bar to toggle its visibility 

## Notes
- In scope of this, we need a way for any component, however deeply nested, to add a global button which is always visible - and probablly we should simplify so that
  - All "global" buttons are always visible (peers of the root context)
  - No button is both global and local

**Comment by hvanyo** [comment]
Icon can be found on https://jhdfdc.axshare.com/#g=1&p=generic_ui&id=sxj4x9

**Comment by schristodoulou** [comment]
Note. Cypress tests will need to be updated.
