### ISSUE TITLE
Component Library: Search Component - Type Ahead

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#800]
## Description
As an end user, I want to search the site and have results start to appear as I am typing in my keywords, so that I do not have to wait for the results page to review the content.

See screenshot to match design 

## Acceptance Criteria
ACs
1. List of potential keyword phrases appears with the first letter typed as a list below the search box (see screenshot attached) 
1. Order is based on frequency and lists no more then 5 items
1. Items list # of results 
1. Item list is at full width of the search field
1. search results do not contain punctuation 
1. Responsive behavior should be the same on all formats

 

## Attachments
<img title="Demo_Canvas_Global_Digital_Solutions.jpg" src="https://user-images.githubusercontent.com/59970745/104342141-85357e80-54c8-11eb-830a-acfd9f7fa60e.jpg" width="200" />

**Comment by asiarheyeu** [comment]
Closed as completed
