### ISSUE TITLE
Images still missing from Documentation

### ISSUE THREAD

**Issue by malachye** [johnsonandjohnson/Bodiless-JS#810]
Every image used in package must be specified in the package's bodiless.docs.json file. 
- Add the proper image assets to the appropriate bodiless.docs.json file.

Testing:
Check that all images appear correctly at https://johnsonandjohnson.github.io/Bodiless-JS/#/Components/RichText

**Comment by asiarheyeu** [comment]
Completed and passed UAT. Closing
