### ISSUE TITLE
Bodiless touts refresh repackaging & renaming card

### ISSUE THREAD

**Issue by hvanyo** [johnsonandjohnson/Bodiless-JS#848]
## Description
Rename touts -> cards to be more consistent with other design systems and repackage it.

## Technical refactoring checklist:
- Export a clean version with no styling or schema
- Where appropriate, export layout tokens (eg. touts)
- Export a default schema (?)
- Where needed, refactor API for better DX
- Refactor reference implementation in starter site/test site
- Reorganize according to new principles
- Provide basic styling tokens with metadata
- Provide basic schema tokens
- Provide storybook documentation (or equivalent in pure Bodiless)
- 
## Acceptance Criteria
1. Copy Touts in their own bodiless package : @bodiless/card and do any necessary refactoring.   
2. Refactor name of tout -> card.
3. Existing Touts in the Bodiless Organisms Package remains unchanged to avoid breaking changes (will be deprecated in the future) 
4. Self document via api documentation and update the tout documentation
5. The test and starter sites are refactored to use the new patterns.

**Comment by TatsianaMiraniuk** [comment]
Hi @Guilherme-Almeida-Zeni

please see **issue_1**:
Docs need to be updated - 'touts'/'tout' are still there

**Steps to Reproduce:**
1. in Edit env, click Docs icon to open /___docs/#/
2. search for 'tout'

**Actual Results:**
'touts'/'tout' are still used
![Screen Shot 2021-04-05 at 3 06 29 PM](https://user-images.githubusercontent.com/3224040/113614460-889c5a00-9620-11eb-9e40-ab521bdcefea.png)

![Screen Shot 2021-04-05 at 2 59 07 PM](https://user-images.githubusercontent.com/3224040/113614088-06ac3100-9620-11eb-9c3e-7a6c50284458.png)

**Expected Results:**
tout is renamed to card (per AC4: .. 'and update the tout documentation')

**Comment by Guilherme-Almeida-Zeni** [comment]
> 1. /___docs/#/

Hi @TatsianaMiraniuk ,

Sorry about the inconvenient, I've just updated the bodiless documentation files (https://github.com/johnsonandjohnson/Bodiless-JS/pull/934/commits/7f9e779f7f5f0564302ccf4df37048bc4223fee2). Please, check it again.

**Comment by irkhodzka** [comment]
Hi @Guilherme-Almeida-Zeni

please see **issue_2**:
Cards in mega menu context menu are still called 'Touts'
**STR:**
1. Go to any page of the web site
2. Switch to edit mode.
3. Click on any place inside mega menu region.
4. In local context menu click on 'Sub' option in Menu Item section.
5. Observe the proposed list of sub menu types.
6. Click on cards submenu type.
7.  Observe body text placeholder 
**Actual Result**:

- Cards in Submenu Types are still called _Touts_. 

- If to select Touts submenu view, there is '_Tout_ body text' in body placeholder
<img width="615" alt="Screenshot_3" src="https://user-images.githubusercontent.com/81805756/113694441-6e25b780-96d8-11eb-8a32-fe6bdc125da7.png">
<img width="894" alt="Screenshot_1" src="https://user-images.githubusercontent.com/81805756/113694420-6a923080-96d8-11eb-8eb8-a5148e0867bf.png">

**Expected Result:** 
As per AC2: "Refactor name of tout -> card."

**Comment by Guilherme-Almeida-Zeni** [comment]
> Hi @Guilherme-Almeida-Zeni
> 
> please see **issue_2**:
> Cards in mega menu context menu are still called 'Touts'
> **STR:**
> 
> 1. Go to any page of the web site
> 2. Switch to edit mode.
> 3. Click on any place inside mega menu region.
> 4. In local context menu click on 'Sub' option in Menu Item section.
> 5. Observe the proposed list of sub menu types.
> 6. Click on cards submenu type.
> 7. Observe body text placeholder
>    **Actual Result**:
> 
> * Cards in Submenu Types are still called _Touts_.
> * If to select Touts submenu view, there is '_Tout_ body text' in body placeholder
> 
> <img alt="Screenshot_3" width="615" src="https://user-images.githubusercontent.com/81805756/113694441-6e25b780-96d8-11eb-8a32-fe6bdc125da7.png">
> 
> <img alt="Screenshot_1" width="894" src="https://user-images.githubusercontent.com/81805756/113694420-6a923080-96d8-11eb-8eb8-a5148e0867bf.png">
> 
> **Expected Result:**
> As per AC2: "Refactor name of tout -> card."

Hi @irkhodzka ,

The refactor for Touts references inside Menu is not possible right now because the definition is in the Menu component inside organisms package, which should not be refactored in order to not impact other sites using Bodiless. I think we discussed that a few weeks ago on a daily standup meeting, but no problems for me in case you raise that to a new discussion on standup meeting again.

**Comment by TatsianaMiraniuk** [comment]
> > 1. /___docs/#/
> 
> Hi @TatsianaMiraniuk ,
> 
> Sorry about the inconvenient, I've just updated the bodiless documentation files ([7f9e779](https://github.com/johnsonandjohnson/Bodiless-JS/commit/7f9e779f7f5f0564302ccf4df37048bc4223fee2)). Please, check it again.

Hi @Guilherme-Almeida-Zeni ,
there are still search results for 'tout'. not existing page is returned in the results: 
![Screen Shot 2021-04-06 at 12 20 46 PM](https://user-images.githubusercontent.com/3224040/113744405-b215be00-96d2-11eb-818e-5612df47c688.png)
Can you please recheck?

Thanks,
Tatsiana

**Comment by TatsianaMiraniuk** [comment]
> > Hi @Guilherme-Almeida-Zeni
> > please see **issue_2**:
> > Cards in mega menu context menu are still called 'Touts'
> > **STR:**
> > 
> > 1. Go to any page of the web site
> > 2. Switch to edit mode.
> > 3. Click on any place inside mega menu region.
> > 4. In local context menu click on 'Sub' option in Menu Item section.
> > 5. Observe the proposed list of sub menu types.
> > 6. Click on cards submenu type.
> > 7. Observe body text placeholder
> >    **Actual Result**:
> > 
> > 
> > * Cards in Submenu Types are still called _Touts_.
> > * If to select Touts submenu view, there is '_Tout_ body text' in body placeholder
> > 
> > <img alt="Screenshot_3" width="615" src="https://user-images.githubusercontent.com/81805756/113694441-6e25b780-96d8-11eb-8a32-fe6bdc125da7.png">
> > <img alt="Screenshot_1" width="894" src="https://user-images.githubusercontent.com/81805756/113694420-6a923080-96d8-11eb-8eb8-a5148e0867bf.png">
> > **Expected Result:**
> > As per AC2: "Refactor name of tout -> card."
> 
> Hi @irkhodzka ,
> 
> The refactor for Touts references inside Menu is not possible right now because the definition is in the Menu component inside organisms package, which should not be refactored in order to not impact other sites using Bodiless. I think we discussed that a few weeks ago on a daily standup meeting, but no problems for me in case you raise that to a new discussion on standup meeting again.

per discussion, gap ticket has been created #958

**Comment by Guilherme-Almeida-Zeni** [comment]
> > > 1. /___docs/#/
> > 
> > 
> > Hi @TatsianaMiraniuk ,
> > Sorry about the inconvenient, I've just updated the bodiless documentation files ([7f9e779](https://github.com/johnsonandjohnson/Bodiless-JS/commit/7f9e779f7f5f0564302ccf4df37048bc4223fee2)). Please, check it again.
> 
> Hi @Guilherme-Almeida-Zeni ,
> there are still search results for 'tout'. not existing page is returned in the results:
> ![Screen Shot 2021-04-06 at 12 20 46 PM](https://user-images.githubusercontent.com/3224040/113744405-b215be00-96d2-11eb-818e-5612df47c688.png)
> Can you please recheck?
> 
> Thanks,
> Tatsiana

Hi @TatsianaMiraniuk ,

Hm.. this is weird. I saw there were some docs references still outdated but I've just commited then, however, despite I check the doc pages in my local environment and they have changed to "cards", they still can be found as "tout" in the search. I'll need to dig in a little more because I might be missing some tech step to update the search itself.

BTW, the docs about menu touts, I still kept it since I understand it will be updated after refactor on #958. For the FClasses + Token packages docs, I still waiting confirmation on the Teams if we should refactor both, so I can update docs for them as well. In case you think it's okay to update all the docs, even the component itself is not fully refactored, just let me know then we do it.

**Comment by hvanyo** [comment]
@Guilherme-Almeida-Zeni  @TatsianaMiraniuk  docsify search caches, go into Application Tab, Local storage and delete the docisfy.search.xxx file.

**Comment by Guilherme-Almeida-Zeni** [comment]
> @Guilherme-Almeida-Zeni @TatsianaMiraniuk docsify search caches, go into Application Tab, Local storage and delete the docisfy.search.xxx file.

Thanks, @hvanyo !

It works just fine, thanks!

@TatsianaMiraniuk , please, check it again. In the search, I only see now references for menu touts, which I think we can as part of #958.

**Comment by TatsianaMiraniuk** [comment]
Issue_1 is fixed. Thanks!
