### ISSUE TITLE
Clone page from another site

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#86]
## User Story

- AS A Content Editor
- I WANT to be able to clone a page from another bodiless site
- SO THAT I can easily reuse content

### Acceptance Criteria

AC1.
There exists a tool which can take a url+site as input and create a new changeset for the site
which adds a page matching the page at the specified url.

AC2.
The above only works if the site at the specified URL is a bodiless site with a repository known to inventory services.

### Implementation Notes

** All components utilized on the page are already included within site.
** If the components are not there, the editor may get 'WSOD' and need developer, it would not provide or try fix.

**Comment by hvanyo** [comment]
Closing as old..
