### ISSUE TITLE
Flow Container RTL: the components are shown outside of the Component Picker if 2nd, 3rd views are selected

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#868]
## Description
Flow Container RTL: the components are shown outside of the Component Picker if 2nd, 3rd views are selected

### Steps to reproduce:
1. in Edit env, open /flow-container-rtl/
2. switch to edit mode
3. open the Component picker
4. change View mode to 2 components in a row (click 2nd icon below Search box)
### Actual result
the components are outside the Component Picker area 
![Screen Shot 2021-02-18 at 4 31 15 PM](https://user-images.githubusercontent.com/3224040/108424784-9e3bf880-7207-11eb-9f87-82f26fa54a36.png)

5. click 1st icon below Search box
the components are outside the Component Picker area (not visible until a page get zoomed out)
![Screen Shot 2021-02-18 at 4 31 39 PM](https://user-images.githubusercontent.com/3224040/108424763-99774480-7207-11eb-8d2e-668e02e00b24.png)

### Expected result
the components are inside the Component Picker area 

reproduced in Master

**Comment by hvanyo** [comment]
RTL will not be addressed until needed.
