### ISSUE TITLE
Component Picker: An icon with 3 items in a row is used for viewing 2 components in a row

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#869]
## Description
Component Picker: An icon with 3 items in a row is used for viewing 2 components in a row

### Steps to reproduce:
1. in Edit env, open any page with a flow container, e.g. /flow-container/
2. switch to edit mode
3. open the Component picker
### Actual result
2nd icon for selecting the view doesn't correspond the actual number of the items in a row
![Screen Shot 2021-02-18 at 4 46 01 PM](https://user-images.githubusercontent.com/3224040/108425862-12c36700-7209-11eb-9838-03df24b9e652.png)

### Expected result
an icon with 2 items in a row should be used

reproduced in Master

**Comment by asiarheyeu** [comment]
Closed as won't fix
