### ISSUE TITLE
Structured Data: JSON-LD Video Schema

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#875]
## Description
*Description:* To support optimal SEO CanvasX must support various Structured Data Schemas. The Video Schema should be auto when video is used on a page. Video Schema should be applicable for YouTube and non-YouTube hosted videos. 

*Google Developer Documentation:* https://developers.google.com/search/docs/data-types/video

*Notes:* There are 4 different types of Video schemas (VideoObject, BroadcastEvent, ItemList, Clip) 
For the purpose of JnJ CanvasX should support VideoObject: https://schema.org/VideoObject

**Required Elements By Google**

*Page Type* 
|*Required Elements*|
|description|
|name|
|thumbnailURL|
|uploaddate|

 
|Recommended Properties|
|---|
|contentURL|
|duration|
|embedURL|
|expires|
|hasPart|
|interactionStatistic|
|publication|
|regionsAllowed|

 
## Acceptance Criteria
AC1. There is a video schema API that renders the existing Youtube video data into JSON in the helmet
* JSON generates automatically if possible with the minimum required data  ideally with all pieces
- JSON is correctly formatted when generated and can be verified in the Structured Data Testing Tool https://search.google.com/structured-data/testing-tool/u/0/
- JSON includes the required elements
- JSON allows for recommended elements

AC2. If multiple videos are on a page then they are rendered as multiple video JSON schema.

AC3. Youtube Video Data for the JSON-LD will be retrieved via https://www.googleapis.com and stored with the videos node key when the YouTube configuration check is clicked and a messaged is displayed "On save the schema.org video data will be applied." 
 
AC4. The test site utilizes the above API to render the video schema .

**Comment by hvanyo** [comment]
Implemented at proprietary level.
