### ISSUE TITLE
Flow Container/Flow Container RTL: List component is not aligned with other components

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#884]
## Description
Flow Container/Flow Container RTL: List component is not aligned with other components

### Steps to reproduce:
1. in Edit env, open /flow-container/
2. switch to Edit mode
3. in  Flow Container, add List component
4. add a few items
5. add some other components, e.g. Accordion, Landscape Image
### Actual result
List component is not aligned with other components
![Screen Shot 2021-02-23 at 3 43 26 PM](https://user-images.githubusercontent.com/3224040/108909793-010c0600-75f3-11eb-9d29-9e5e263f3e5d.png)

![Screen Shot 2021-02-23 at 3 43 51 PM](https://user-images.githubusercontent.com/3224040/108909835-0ff2b880-75f3-11eb-8c5f-cca422756ca1.png)

### Expected result
List component is aligned with other components

NOTE: the same issue is on /flow-container-rtl/

reproduced in Master

**Comment by hvanyo** [comment]
RTL will not be addressed until needed.
