### ISSUE TITLE
Touts: Placeholder title for asToutOverlayTitle isn't fully visible

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#889]
## Description
Touts: Placeholder title for asToutOverlayTitle isn't fully visible

### Steps to reproduce:
1. in Edit env, open /touts/,
2. scroll to a tout that has a Title on an image (asToutOverlayTitle)

### Actual result
Placeholder title isn't fully visible
![Screen Shot 2021-02-24 at 9 52 55 AM](https://user-images.githubusercontent.com/3224040/109020020-91942600-7687-11eb-9f66-b3485456af01.png)

3. switch to Edit mode

### Actual result
Placeholder title isn't fully visible
![Screen Shot 2021-02-24 at 9 52 50 AM](https://user-images.githubusercontent.com/3224040/109020098-a83a7d00-7687-11eb-9254-6b16976cb405.png)

### Expected Results
Placeholder title is fully visible

reproduced in Master

**Comment by Guilherme-Almeida-Zeni** [comment]
Closing since has been fixed and tested on #934 .
