### ISSUE TITLE
RTL: Menu items labels are not right aligned.

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#893]
## Description
RTL: Menu items labels are not right aligned.

### Steps to reproduce:
1. in Edit or Static env, open /flow-container-rtl/
2. hover over on an item with a submenu

### Actual result
The labels are left aligned  (issue for Top level items and Submenu items)
![Screen Shot 2021-02-24 at 4 44 25 PM](https://user-images.githubusercontent.com/3224040/109069892-d3d95980-76bf-11eb-9651-27deb58025ba.png)

### Expected result
Menu items are right aligned

reproduced in Master

**Comment by hvanyo** [comment]
RTL will not be addressed until needed.
