### ISSUE TITLE
RTL: Admin Menu, Local Context Menus issues

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#894]
## Description
RTL: Admin Menu, Local Context Menus issues

### Steps to reproduce:
1. in Edit env, open /flow-container-rtl/
2. switch to Edit mode
3. check all Admin Menu forms
### Actual result
 - the dot locates incorrectly in English sentences
 - scrollbars (Alert; History) at the left
 - a page path, template (New Page); an image url; URL (Share); History items are in RTL
 - icons in File: RTL (no space between Revert and History)
 
![Screen Shot 2021-02-25 at 9 10 04 AM](https://user-images.githubusercontent.com/3224040/109165800-f7e17d00-7749-11eb-8ff8-2707f665c320.png)
![Screen Shot 2021-02-25 at 9 10 12 AM](https://user-images.githubusercontent.com/3224040/109165799-f748e680-7749-11eb-9e8f-0aa5162ce61c.png)
![Screen Shot 2021-02-25 at 9 11 21 AM](https://user-images.githubusercontent.com/3224040/109165785-f57f2300-7749-11eb-9b7e-0b01b75670b7.png)
![Screen Shot 2021-02-25 at 9 10 26 AM](https://user-images.githubusercontent.com/3224040/109165798-f6b05000-7749-11eb-8770-a68fe4b5ed56.png)
![Screen Shot 2021-02-25 at 9 11 32 AM](https://user-images.githubusercontent.com/3224040/109165779-f3b55f80-7749-11eb-9433-32e8f8f0b778.png)
![Screen Shot 2021-02-25 at 9 10 33 AM](https://user-images.githubusercontent.com/3224040/109165793-f617b980-7749-11eb-8914-5fd6b0eecefb.png)

4. check Local Context Menu in different components
### Actual result
- RTL is applied;
- No space between 'Delete' and 'Swap'
- Submenus types checkboxes
![Screen Shot 2021-02-25 at 9 12 37 AM](https://user-images.githubusercontent.com/3224040/109166963-43485b00-774b-11eb-91e8-ae1d0a278f7b.png)
![Screen Shot 2021-02-25 at 9 12 01 AM](https://user-images.githubusercontent.com/3224040/109166969-45121e80-774b-11eb-9a01-c8f6d9cd4e48.png)
![Screen Shot 2021-02-25 at 4 16 29 PM](https://user-images.githubusercontent.com/3224040/109218824-e7022d00-7784-11eb-9f69-6881fa4860fc.png)

### Expected Results
to determine....

reproduced in Master

**Comment by hvanyo** [comment]
RTL will not be addressed until needed.
