### ISSUE TITLE
Need ability to create anchor links

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#904]
## Description
As a content editor I want to create anchor links on sections/copy/etc. so that I can use these urls elsewhere to drop users directly to this content.

The use case here is the anchors were added to the h2's faq sections.

https://www.microlax.com.mx/faq#informaci%C3%B3n-general-acerca-de-microlax-sup-sup

 

 
## Acceptance Criteria
AC1. There is an HOC that adds the following effect to a component
- Adds a local context button, in the context group anchor and merges down
- This button opens a form that allows for the entering of on id which has a placeholder value of "Descriptive ID"
- This button label is "add" if there is no id, and "edit" if there is an id
- The button icon is "Tag" icon.
- This id is then applied to the component if specified 
- For form validation/normalization of id:
-- If a # is entered, the # is removed automatically before saving.
-- The id is transformed (spaces to dashes otherwise encode it) to create valid anchor , the transformed anchor id value appears underneath the ID input field of the form. 

AC2. The test site has the standard H2 wrapped with the above HOC (scoped to RTE H2 and Accordion TItle H2)

AC3. If the anchor ID is empty then nothing is added

AC4. If this HOC is applied to a component that already has data, the existing data is still rendered correctly (the anchor id value is added as sidecar)

AC5. Address Bug "Seach is overriding the #anchor link functionality" is resolved

**Comment by hvanyo** [comment]
@ali @VancheeZze  @konst8 
the sub AC "If a # is entered, the # is removed automatically before saving." add complexity and time that may not be available.  The intent of this was to self-correct a content editor if they saw add anchor "#something" it would autostrip the prefix # and then save it as "something".  Ali's implementation it will give invalid anchor and IMO, its probably better to correct the content editor and enforce them to put it correctly.  So for now proposing we drop the AC unless Ali can do it his timeframe and leaving that to his choice.
