### ISSUE TITLE
Trigger redeploy of p.sh edit environment on PR update

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#91]
## User Story

- AS A Bodiless-JS Developer
- I WANT changes delivered to the edit environment when I update a PR
- SO THAT it can be tested immediately.

### Acceptance Criteria

AC1
When a PR is updated
The changes are delivered to the edit environment

AC2.
If the update does not involve modification of package-lock.json
The edit environment skips "lerna bootstrap"

AC3.
If the update only involves modification of site level code
The app is not restarted

AC4.
If the pr has a specific label ("testing-in-progress"?)
The changes are not pushed automatically.

### Implementation Notes

Do this in Travis.

**Comment by hvanyo** [comment]
Close as not fixing
