### ISSUE TITLE
Link form: 'url' field is not in focus after first click

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#913]
## Description
Link form: 'url' field is not in focus after first click

### Steps to reproduce:
1.  open Edit env, 
2. switch to Edit Mode
3. open any Link Form, e.g. in Mega Menu
4. click 'url' field

### Actual result
the field is not in focus. Second click is required.

### Expected results
the field gets focused after first click

reproduced in Master

**Comment by irkhodzka** [comment]
the issue is not reproducible anymore
