### ISSUE TITLE
Improve types in fclasses

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#919]
## User Story

As a developer
I want robust types for tokens and other hoc's
So I don't waste time struggling with obscure type errors.

## Acceptance Criteria

AC1. The HOC and Token types are improved so that we can infer and override the props of a resulting component.
AC2. Any HOC/Token exported by fclasses, bodiless-core or bodiless components is typed as a Token or HOC.

## Testing
No in-depth testing just smoke testing

**Comment by asiarheyeu** [comment]
Closed as completed
