### ISSUE TITLE
Title element rendered in body instead of head

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#931]
### Steps to reproduce

Open homepage and view html source.

### Expected result

Title tag is in html head section

### Actual result

Title tag is rendered inside 
<img width="1079" alt="BodilessJS Test Site 2021-03-19 08-56-58" src="https://user-images.githubusercontent.com/1812250/111783924-222de280-8891-11eb-9280-8829f9b7d64c.png">
body section

**Comment by hvanyo** [comment]
This is isoalted to test site so closing.
VitalDS demo is placing title in <head>
![2022-06-09_13-23-09](https://user-images.githubusercontent.com/58534559/172917828-2df7af8f-2fc1-4109-981b-4f22a1ad03d2.jpg)
