### ISSUE TITLE
MegaMenu: the submenus of the demo menu  overlaps the submenu of global menu (/menu/)

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#954]
## Description
MegaMenu: the submenus of the demo menu  overlaps the submenu of global menu (/menu/)

### Steps to reproduce
1. open Edit env, /menu/ page
2. switch to Edit mode
3. in the demo MegaMenu, add a submenu item 
4. add text in the submenu
5. keep the submenu open (click on it)
6. hover over 'Components' in the global MegaMenu

### Actual result
 the submenus of the demo menu  overlaps the submenu of global menu
![Screen Shot 2021-04-05 at 4 05 30 PM](https://user-images.githubusercontent.com/3224040/113621603-d073af00-9629-11eb-90a1-73bca125a493.png)

### Expected result
the submenu of the global menu shows on top of all inner parts of any page

### Affected Version
reproduced in Master

**Comment by hvanyo** [comment]
Odds are this won't happen on normal sites as they won't have too menus. So clsoing as won't fix.
