### ISSUE TITLE
Carousel: Image Upload form is broken

### ISSUE THREAD

**Issue by TatsianaMiraniuk** [johnsonandjohnson/Bodiless-JS#960]
## Description
Carousel: Image Upload form is broken

### Steps to reproduce
1. open Edit env, /carousel/ page
2. switch to Edit mode
3. click Carousel slide to get Local Context Menu
4. click Image Select
5. click on 'drag a file or click here to upload'

### Actual result
nothing happens

6. click Alt/Text/Src fields

### Actual result
nothing happens - the fields are locked

### Expected result
Image Upload form works without issues, all parameters can be edited; image can be uploaded

### Affected Version
reproduced in Master

**Comment by irkhodzka** [comment]
The issue was verified and it is fixed now.

**Comment by hvanyo** [comment]
Closed as fixed.
