### ISSUE TITLE
Border width added by ContextWrapper on Edit mode

### ISSUE THREAD

**Issue by dewen** [johnsonandjohnson/Bodiless-JS#970]
### Steps to reproduce

- Open Test-Site and go to any page.
- Check page source and look for container div with class `bl-border`

### Expected result

No border width added to container div

### Actual result

These is 1px border added

This could cause design issues on site level, for example, container shadow will add different color to border.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

- If the issue was encountered on a site, please attach your `package.json`
- If the issue was encountered in the Bodiless-JS repo, please link to a
  commit or branch on which the issue occurs.

**Comment by hvanyo** [comment]
Resolved
