### ISSUE TITLE
Missing nuka-carousel dependency on bodiless organisms package

### ISSUE THREAD

**Issue by Guilherme-Almeida-Zeni** [johnsonandjohnson/Bodiless-JS#976]
When syncing my master fork, I had issues because of "nuka-carousel", which is used by Carousel.tsx file at bodiless-organisms package. See evidence below:
![bodiless_package_issue](https://user-images.githubusercontent.com/36273913/116410550-44f5d400-a80b-11eb-944a-7ca4aa11643d.png)

Two ways of solving this:
* Adding "nuka-carousel" dependency on organisms package; or
* Carousel repackage ticket has been merged two days ago, and in case Carousel.tsx inside organism was meant to be removed, and we don't have dependencies on that file, we can simply remove Carousel.tsx.

Please, @hvanyo , @beliayeu , @marcopagliarulo , could anyone please help to confirm if we can remove Carousel.tsx or just add package dependency?

**Note:** I already pushed two different branches to my fork, each one using one of the approaches, so I just need confirmation to move on.

**Comment by hvanyo** [comment]
@Guilherme-Almeida-Zeni   nuka-carousel is no longer removed.  Please remove the dependency and Carousel.tsx :)

**Comment by Guilherme-Almeida-Zeni** [comment]
@hvanyo ,

As we have talked on chat, since Andrei will only take this tomorrow, I'm removing it since it's blocking me from updating my fork.

^cc: @beliayeu .^
